import type { ContentLocale, Locale, Localized } from './categories';

// Sub-topic clusters. Labels are written the way a READER would say them,
// not in internal taxonomy language. Target 5–15 articles per cluster.
// SUBCATEGORY_ORDER controls display order within a category page.

export const SUBCATEGORY_LABELS: Record<string, Localized> = {
  // ---- business ----
  formation: { ms: 'Asas Penubuhan', en: 'Formation fundamentals', zh: '公司设立基础', ta: 'நிறுவன அமைப்பு அடிப்படைகள்' , ja: '会社設立の基礎', ko: '회사 설립 기초', th: 'พื้นฐานการจัดตั้งบริษัท' },
  'choosing-a-structure': { ms: 'Memilih Struktur', en: 'Choosing a structure', zh: '选择商业结构', ta: 'கட்டமைப்பைத் தேர்ந்தெடுத்தல்' , ja: '事業形態の選択', ko: '사업 형태 선택', th: 'การเลือกโครงสร้างธุรกิจ' },
  registration: { ms: 'Prosedur Pendaftaran', en: 'Registration procedures', zh: '注册程序', ta: 'பதிவு நடைமுறைகள்' , ja: '登録手続き', ko: '등록 절차', th: 'ขั้นตอนการจดทะเบียน' },
  licensing: { ms: 'Lesen & Permit', en: 'Licences & permits', zh: '执照与准证', ta: 'உரிமங்கள் & அனுமதிகள்' , ja: 'ライセンス・許可', ko: '인허가 및 허가증', th: 'ใบอนุญาตและใบอนุญาตประกอบการ' },
  'foreign-ownership': { ms: 'Pemilikan & Pelabur Asing', en: 'Foreign founders & ownership', zh: '外资与股权', ta: 'வெளிநாட்டு நிறுவனர்கள் & உரிமை' , ja: '外国資本・出資', ko: '외국인 창업자 및 지분', th: 'ผู้ก่อตั้งต่างชาติและการถือหุ้น' },
  'banking-finance': { ms: 'Perbankan, Kewangan & Kawalan Pertukaran', en: 'Banking, finance & exchange control', zh: '银行、融资与外汇管制', ta: 'வங்கி, நிதி & நாணய மாற்றுக் கட்டுப்பாடு' , ja: '銀行・金融・為替管理', ko: '은행, 금융 및 외환 관리', th: 'การธนาคาร การเงิน และการควบคุมการแลกเปลี่ยนเงินตรา' },
  'contracts-disputes': { ms: 'Kontrak & Pertikaian', en: 'Contracts & disputes', zh: '合约与纠纷', ta: 'ஒப்பந்தங்கள் & தகராறுகள்' , ja: '契約・紛争', ko: '계약 및 분쟁', th: 'สัญญาและข้อพิพาท' },
  'intellectual-property': { ms: 'Harta Intelek', en: 'Intellectual property', zh: '知识产权', ta: 'அறிவுசார் சொத்து' , ja: '知的財産', ko: '지식재산권', th: 'ทรัพย์สินทางปัญญา' },
  'economic-corridors': { ms: 'Koridor Ekonomi', en: 'Where to invest — regions & corridors', zh: '经济走廊与投资地点', ta: 'எங்கு முதலீடு செய்வது — பகுதிகள் & வழித்தடங்கள்' , ja: '投資先——地域・経済回廊', ko: '투자처 — 지역 및 경제 회랑', th: 'แหล่งลงทุน — ภูมิภาคและระเบียงเศรษฐกิจ' },
  locations: { ms: 'Berniaga Mengikut Lokasi', en: 'Doing business by location', zh: '各地经商指南', ta: 'இடம் வாரியாக வணிகம்' , ja: '地域別のビジネス', ko: '지역별 사업', th: 'การทำธุรกิจแยกตามพื้นที่' },
  'digital-compliance': { ms: 'Pematuhan Digital', en: 'Digital compliance', zh: '数字合规', ta: 'டிஜிட்டல் இணக்கம்' , ja: 'デジタルコンプライアンス', ko: '디지털 컴플라이언스', th: 'การปฏิบัติตามกฎระเบียบดิจิทัล' },
  closing: { ms: 'Penstrukturan & Penutupan', en: 'Restructuring & closure', zh: '重组与结业', ta: 'மறுசீரமைப்பு & மூடல்' , ja: '再編・清算', ko: '구조조정 및 폐업', th: 'การปรับโครงสร้างและการเลิกกิจการ' },
  // legacy keys, kept so older articles still label correctly
  ownership: { ms: 'Pemilikan & Pelabur Asing', en: 'Foreign founders & ownership', zh: '外资与股权', ta: 'வெளிநாட்டு நிறுவனர்கள் & உரிமை' , ja: '外国資本・出資', ko: '외국인 창업자 및 지분', th: 'ผู้ก่อตั้งต่างชาติและการถือหุ้น' },
  structuring: { ms: 'Struktur & Entiti', en: 'Structuring & entities', zh: '架构与实体', ta: 'கட்டமைப்பு & நிறுவனங்கள்' , ja: '組織・事業体', ko: '구조 설계 및 사업체', th: 'การจัดโครงสร้างและนิติบุคคล' },
  banking: { ms: 'Perbankan & Kewangan', en: 'Banking & finance setup', zh: '银行与融资', ta: 'வங்கி & நிதி அமைப்பு' , ja: '銀行・金融の準備', ko: '은행 및 금융 준비', th: 'การจัดการด้านการธนาคารและการเงิน' },

  // ---- company secretary ----
  appointment: { ms: 'Pelantikan & Kelayakan', en: 'Appointment & qualification', zh: '委任与资格', ta: 'நியமனம் & தகுதி' , ja: '選任・資格', ko: '선임 및 자격', th: 'การแต่งตั้งและคุณสมบัติ' },
  'statutory-registers': { ms: 'Daftar Berkanun & Rekod', en: 'Statutory registers & records', zh: '法定登记册与记录', ta: 'சட்டப்பூர்வ பதிவேடுகள் & பதிவுகள்' , ja: '法定登録簿・記録', ko: '법정 등록부 및 기록', th: 'ทะเบียนและบันทึกตามกฎหมาย' },
  filings: { ms: 'Penyata Tahunan & Pemfailan', en: 'Annual return & filings', zh: '年报与申报', ta: 'ஆண்டறிக்கை & தாக்கல்கள்' , ja: '年次報告・各種届出', ko: '연차보고 및 신고', th: 'รายงานประจำปีและการยื่นเอกสาร' },
  directors: { ms: 'Tugas & Pendedahan Pengarah', en: "Directors' duties & disclosures", zh: '董事职责与披露', ta: 'இயக்குநர்களின் கடமைகள் & வெளிப்பாடுகள்' , ja: '取締役の義務・開示', ko: "이사의 의무 및 공시", th: 'หน้าที่และการเปิดเผยข้อมูลของกรรมการ' },
  'meetings-resolutions': { ms: 'Mesyuarat & Resolusi', en: 'Meetings & resolutions', zh: '会议与决议', ta: 'கூட்டங்கள் & தீர்மானங்கள்' , ja: '会議・決議', ko: '회의 및 결의', th: 'การประชุมและมติ' },
  'share-capital': { ms: 'Modal Saham & Pemindahan', en: 'Share capital & transfers', zh: '股本与股份转让', ta: 'பங்கு மூலதனம் & பரிமாற்றங்கள்' , ja: '株式資本・譲渡', ko: '주식 자본 및 양도', th: 'ทุนเรือนหุ้นและการโอนหุ้น' },
  'beneficial-ownership': { ms: 'Pemilik Benefisial', en: 'Beneficial ownership', zh: '实益拥有权', ta: 'பயனாளி உரிமை' , ja: '実質的支配者', ko: '실질적 소유자', th: 'ผู้รับผลประโยชน์ที่แท้จริง' },
  governance: { ms: 'Tadbir Urus', en: 'Governance', zh: '公司治理', ta: 'ஆளுகை' , ja: 'コーポレートガバナンス', ko: '지배구조', th: 'ธรรมาภิบาล' },

  // ---- taxation ----
  'corporate-tax': { ms: 'Cukai Korporat', en: 'Corporate tax', zh: '企业税', ta: 'நிறுவன வரி' , ja: '法人税', ko: '법인세', th: 'ภาษีเงินได้นิติบุคคล' },
  'personal-tax': { ms: 'Cukai Individu', en: 'Personal tax', zh: '个人税', ta: 'தனிநபர் வரி' , ja: '個人所得税', ko: '개인소득세', th: 'ภาษีเงินได้บุคคลธรรมดา' },
  'deductions-and-allowances': { ms: 'Potongan & Elaun', en: 'Deductions & allowances', zh: '扣除与津贴', ta: 'கழிவுகள் & கொடுப்பனவுகள்' , ja: '控除・手当', ko: '공제 및 수당', th: 'รายการหักและค่าลดหย่อน' },
  sst: { ms: 'SST', en: 'Sales & Service Tax', zh: '销售与服务税', ta: 'விற்பனை & சேவை வரி (SST)' , ja: '売上・サービス税（SST）', ko: '판매·서비스세(SST)', th: 'ภาษีขายและบริการ (SST)' },
  'e-invoicing': { ms: 'e-Invois', en: 'E-invoicing', zh: '电子发票', ta: 'மின் விலைப்பட்டியல்' , ja: '電子インボイス', ko: '전자 인보이스', th: 'ใบกำกับภาษีอิเล็กทรอนิกส์' },
  'withholding-tax': { ms: 'Cukai Pegangan', en: 'Withholding tax', zh: '预扣税', ta: 'நிறுத்திவைப்பு வரி' , ja: '源泉徴収税', ko: '원천징수세', th: 'ภาษีหัก ณ ที่จ่าย' },
  'international-tax': { ms: 'Cukai Antarabangsa', en: 'International tax', zh: '国际税务', ta: 'சர்வதேச வரி' , ja: '国際税務', ko: '국제 조세', th: 'ภาษีระหว่างประเทศ' },
  'capital-taxes': { ms: 'Cukai Keuntungan Modal', en: 'Taxes on capital', zh: '资本利得税', ta: 'மூலதன வரிகள்' , ja: '資本課税', ko: '자본 과세', th: 'ภาษีจากทุน' },
  'stamp-duty': { ms: 'Duti Setem', en: 'Stamp duty', zh: '印花税', ta: 'முத்திரை வரி' , ja: '印紙税', ko: '인지세', th: 'อากรแสตมป์' },
  incentives: { ms: 'Insentif Cukai', en: 'Tax incentives', zh: '税务优惠', ta: 'வரி ஊக்கத்தொகைகள்' , ja: '税制優遇', ko: '세제 혜택', th: 'สิทธิประโยชน์ทางภาษี' },
  'tax-administration': { ms: 'Pentadbiran Cukai', en: 'Tax administration', zh: '税务行政', ta: 'வரி நிர்வாகம்' , ja: '税務行政', ko: '세무 행정', th: 'การบริหารจัดเก็บภาษี' },

  // ---- accounting ----
  standards: { ms: 'Piawaian Perakaunan', en: 'Accounting standards', zh: '会计准则', ta: 'கணக்கியல் தரநிலைகள்' , ja: '会計基準', ko: '회계 기준', th: 'มาตรฐานการบัญชี' },
  records: { ms: 'Rekod Perakaunan', en: 'Accounting records', zh: '会计记录', ta: 'கணக்கியல் பதிவுகள்' , ja: '会計記録', ko: '회계 기록', th: 'บันทึกทางบัญชี' },
  'financial-statements': { ms: 'Penyata Kewangan & MBRS', en: 'Financial statements & MBRS', zh: '财务报表与 MBRS', ta: 'நிதி அறிக்கைகள் & MBRS' , ja: '財務諸表・MBRS', ko: '재무제표 및 MBRS', th: 'งบการเงินและ MBRS' },
  bookkeeping: { ms: 'Simpan Kira', en: 'Bookkeeping', zh: '簿记', ta: 'கணக்குப் பதிவு' , ja: '簿記', ko: '부기', th: 'การทำบัญชี' },
  'financial-year': { ms: 'Tahun Kewangan', en: 'Financial year end', zh: '财政年结', ta: 'நிதியாண்டு முடிவு' , ja: '会計年度末', ko: '회계연도 말', th: 'วันสิ้นรอบปีบัญชี' },

  // ---- audit ----
  requirements: { ms: 'Keperluan & Pengecualian', en: 'Requirements & exemption', zh: '审计要求与豁免', ta: 'தேவைகள் & விலக்கு' , ja: '監査要件・免除', ko: '요건 및 면제', th: 'ข้อกำหนดและการยกเว้น' },
  'audit-appointment': { ms: 'Melantik Juruaudit', en: 'Appointing an auditor', zh: '委任审计师', ta: 'தணிக்கையாளர் நியமனம்' , ja: '監査人の選任', ko: '감사인 선임', th: 'การแต่งตั้งผู้สอบบัญชี' },
  fees: { ms: 'Yuran Audit', en: 'Audit fees', zh: '审计费用', ta: 'தணிக்கைக் கட்டணங்கள்' , ja: '監査報酬', ko: '감사 보수', th: 'ค่าธรรมเนียมการตรวจสอบบัญชี' },
  process: { ms: 'Proses Audit', en: 'The audit process', zh: '审计流程', ta: 'தணிக்கை நடைமுறை' , ja: '監査の流れ', ko: '감사 절차', th: 'ขั้นตอนการตรวจสอบบัญชี' },
  reporting: { ms: 'Jenis Laporan', en: 'Report types', zh: '报告类型', ta: 'அறிக்கை வகைகள்' , ja: '報告書の種類', ko: '보고서 종류', th: 'ประเภทของรายงาน' },

  // ---- employment ----
  'employment-law-basics': { ms: 'Asas Undang-Undang Pekerjaan', en: 'Employment law basics', zh: '劳动法基础', ta: 'வேலைவாய்ப்புச் சட்ட அடிப்படைகள்' , ja: '労働法の基礎', ko: '고용법 기초', th: 'พื้นฐานกฎหมายแรงงาน' },
  'hiring-and-contracts': { ms: 'Pengambilan & Kontrak', en: 'Hiring & contracts', zh: '招聘与合约', ta: 'பணியமர்த்தல் & ஒப்பந்தங்கள்' , ja: '採用・雇用契約', ko: '채용 및 계약', th: 'การจ้างงานและสัญญา' },
  'payroll-statutory': { ms: 'Gaji & Caruman Berkanun', en: 'Payroll & statutory', zh: '薪资与法定缴纳', ta: 'ஊதியம் & சட்டப்பூர்வக் கட்டணங்கள்' , ja: '給与・法定拠出', ko: '급여 및 법정 부담금', th: 'เงินเดือนและเงินสมทบตามกฎหมาย' },
  'leave-and-welfare': { ms: 'Cuti & Kebajikan', en: 'Leave, benefits & welfare', zh: '假期与福利', ta: 'விடுப்பு, சலுகைகள் & நலன்' , ja: '休暇・福利厚生', ko: '휴가, 복리후생 및 복지', th: 'การลา สวัสดิการ และประโยชน์' },
  'termination-retrenchment': { ms: 'Penamatan & Pemberhentian', en: 'Termination & retrenchment', zh: '解雇与裁员', ta: 'பணிநீக்கம் & பணிக்குறைப்பு' , ja: '解雇・人員削減', ko: '해고 및 정리해고', th: 'การเลิกจ้างและการปลดพนักงาน' },
  'foreign-workers-expatriates': { ms: 'Pekerja Asing & Ekspatriat', en: 'Foreign workers & expatriates', zh: '外籍员工与外派人员', ta: 'வெளிநாட்டுத் தொழிலாளர்கள் & வெளிநாட்டவர்கள்' , ja: '外国人労働者・駐在員', ko: '외국인 근로자 및 주재원', th: 'แรงงานต่างชาติและชาวต่างชาติ' },
  hiring: { ms: 'Pengambilan Pekerja', en: 'Hiring', zh: '招聘', ta: 'பணியமர்த்தல்' , ja: '採用', ko: '채용', th: 'การจ้างงาน' },
  'labour-law': { ms: 'Undang-Undang Buruh', en: 'Labour law', zh: '劳工法', ta: 'தொழிலாளர் சட்டம்' , ja: '労働法', ko: '노동법', th: 'กฎหมายแรงงาน' },

  // ---- states ----
  peninsular: { ms: 'Semenanjung', en: 'Peninsular Malaysia', zh: '马来半岛', ta: 'தீபகற்ப மலேசியா' , ja: '半島マレーシア', ko: '반도 말레이시아', th: 'คาบสมุทรมาเลเซีย (Peninsular Malaysia)' },
  borneo: { ms: 'Borneo', en: 'Borneo', zh: '婆罗洲', ta: 'போர்னியோ' , ja: 'ボルネオ', ko: '보르네오', th: 'เกาะบอร์เนียว (Borneo)' },
  territories: { ms: 'Wilayah Persekutuan', en: 'Federal Territories', zh: '联邦直辖区', ta: 'கூட்டாட்சிப் பிரதேசங்கள்' , ja: '連邦直轄区', ko: '연방 직할구', th: 'ดินแดนสหพันธ์ (Federal Territories)' },
  'state-government': { ms: 'Kerajaan Negeri', en: 'State government', zh: '州政府', ta: 'மாநில அரசாங்கம்' , ja: '州政府', ko: '주 정부', th: 'รัฐบาลของรัฐ' },

  // ---- living: transport ----
  'public-transport': { ms: 'Pengangkutan Awam', en: 'Public transport', zh: '公共交通', ta: 'பொதுப் போக்குவரத்து' , ja: '公共交通', ko: '대중교통', th: 'ระบบขนส่งสาธารณะ' },
  driving: { ms: 'Memandu', en: 'Driving', zh: '驾驶', ta: 'வாகனம் ஓட்டுதல்' , ja: '運転', ko: '운전', th: 'การขับรถ' },
  'vehicles-tolls': { ms: 'Kenderaan & Tol', en: 'Vehicles & tolls', zh: '车辆与过路费', ta: 'வாகனங்கள் & சுங்கச்சாவடி' , ja: '車両・通行料', ko: '차량 및 통행료', th: 'ยานพาหนะและค่าผ่านทาง' },
  // ---- living: money & daily life ----
  'banking-payments': { ms: 'Perbankan & Pembayaran', en: 'Banking & payments', zh: '银行与支付', ta: 'வங்கி & கட்டணங்கள்' , ja: '銀行・決済', ko: '은행 및 결제', th: 'การธนาคารและการชำระเงิน' },
  'personal-tax-statutory': { ms: 'Cukai & Caruman', en: 'Tax & statutory', zh: '税务与法定缴纳', ta: 'வரி & சட்டப்பூர்வக் கட்டணங்கள்' , ja: '税・法定拠出', ko: '세금 및 법정 부담금', th: 'ภาษีและเงินสมทบตามกฎหมาย' },
  'everyday-admin': { ms: 'Urusan Harian', en: 'Everyday admin', zh: '日常事务', ta: 'அன்றாட நிர்வாகப் பணிகள்' , ja: '日常の手続き', ko: '일상 행정', th: 'งานธุรการในชีวิตประจำวัน' },
  // ---- living: settling in ----
  'visas-passes': { ms: 'Visa & Pas', en: 'Visas & passes', zh: '签证与准证', ta: 'விசாக்கள் & அனுமதிச்சீட்டுகள்' , ja: 'ビザ・パス', ko: '비자 및 패스', th: 'วีซ่าและใบอนุญาตพำนัก' },
  documents: { ms: 'Dokumen', en: 'Documents', zh: '证件', ta: 'ஆவணங்கள்' , ja: '証明書類', ko: '증명 서류', th: 'เอกสาร' },
  // ---- living: cost of living / housing / healthcare ----
  overview: { ms: 'Gambaran', en: 'Overview', zh: '概览', ta: 'மேலோட்டம்' , ja: '概要', ko: '개요', th: 'ภาพรวม' },
  'by-city': { ms: 'Mengikut Bandar', en: 'By city', zh: '按城市', ta: 'நகரம் வாரியாக' , ja: '都市別', ko: '도시별', th: 'แยกตามเมือง' },
  renting: { ms: 'Menyewa', en: 'Renting', zh: '租房', ta: 'வாடகை' , ja: '賃貸', ko: '임대', th: 'การเช่าที่พัก' },
  buying: { ms: 'Membeli Rumah', en: 'Buying', zh: '购房', ta: 'வீடு வாங்குதல்' , ja: '住宅購入', ko: '주택 구입', th: 'การซื้อบ้าน' },
  'home-ownership': { ms: 'Pemilikan & Cukai', en: 'Ownership & tax', zh: '产权与税', ta: 'உரிமை & வரி' , ja: '所有権・税', ko: '소유권 및 세금', th: 'กรรมสิทธิ์และภาษี' },
  community: { ms: 'Kejiranan', en: 'Community living', zh: '社区生活', ta: 'சமூக வாழ்க்கை' , ja: 'コミュニティ生活', ko: '커뮤니티 생활', th: 'การใช้ชีวิตในชุมชน' },
  utilities: { ms: 'Utiliti', en: 'Utilities', zh: '水电网络', ta: 'பயன்பாட்டு சேவைகள்' , ja: 'ライフライン', ko: '공공요금', th: 'สาธารณูปโภค' },
  'using-the-system': { ms: 'Menggunakan Sistem', en: 'Using the system', zh: '使用系统', ta: 'அமைப்பைப் பயன்படுத்துதல்' , ja: '制度の使い方', ko: '제도 이용하기', th: 'การใช้ระบบบริการ' },
  insurance: { ms: 'Insurans Perubatan', en: 'Medical insurance', zh: '医疗保险', ta: 'மருத்துவக் காப்பீடு' , ja: '医療保険', ko: '의료 보험', th: 'ประกันสุขภาพ' },
  specialised: { ms: 'Penjagaan Khusus', en: 'Specialised care', zh: '专项护理', ta: 'சிறப்புப் பராமரிப்பு' , ja: '専門医療', ko: '전문 진료', th: 'การดูแลเฉพาะทาง' },
  schooling: { ms: 'Persekolahan', en: 'Schooling', zh: '就学', ta: 'பள்ளிக் கல்வி' , ja: '就学', ko: '학교 교육', th: 'การเรียนในโรงเรียน' },
  exams: { ms: 'Peperiksaan', en: 'Exams', zh: '考试', ta: 'தேர்வுகள்' , ja: '試験', ko: '시험', th: 'การสอบ' },
  tertiary: { ms: 'Pengajian Tinggi', en: 'Higher education', zh: '高等教育', ta: 'உயர்கல்வி' , ja: '高等教育', ko: '고등 교육', th: 'การศึกษาระดับอุดมศึกษา' },
  financing: { ms: 'Pembiayaan', en: 'Financing', zh: '教育资助', ta: 'நிதியுதவி' , ja: '教育資金', ko: '교육비 지원', th: 'เงินทุนการศึกษา' },
  support: { ms: 'Sokongan Pembelajaran', en: 'Learning support', zh: '学习支持', ta: 'கற்றல் ஆதரவு' , ja: '学習支援', ko: '학습 지원', th: 'การสนับสนุนการเรียนรู้' },
  skills: { ms: 'Latihan Kemahiran', en: 'Skills training', zh: '技能培训', ta: 'திறன் பயிற்சி' , ja: '技能訓練', ko: '기술 훈련', th: 'การฝึกทักษะ' },

  // ---- malaysia (history & identity) ----
  'early-kingdoms': { ms: 'Kerajaan Awal', en: 'Early kingdoms', zh: '早期王国', ta: 'ஆரம்பகால இராச்சியங்கள்' , ja: '初期の王国', ko: '초기 왕국', th: 'อาณาจักรยุคแรก' },
  sultanates: { ms: 'Kesultanan Melayu', en: 'Malay sultanates', zh: '马来苏丹王朝', ta: 'மலாய் சுல்தானகங்கள்' , ja: 'マレー・スルタン朝', ko: '말레이 술탄국', th: 'รัฐสุลต่านมลายู' },
  colonial: { ms: 'Zaman Penjajahan', en: 'Colonial era', zh: '殖民时代', ta: 'காலனித்துவ காலம்' , ja: '植民地時代', ko: '식민 시대', th: 'ยุคอาณานิคม' },
  occupation: { ms: 'Pendudukan Jepun', en: 'Japanese occupation', zh: '日据时期', ta: 'ஜப்பானியர் ஆக்கிரமிப்பு' , ja: '日本占領', ko: '일본 점령기', th: 'การยึดครองของญี่ปุ่น' },
  independence: { ms: 'Ke Arah Kemerdekaan', en: 'Towards independence', zh: '迈向独立', ta: 'சுதந்திரத்தை நோக்கி' , ja: '独立へ', ko: '독립을 향하여', th: 'สู่เอกราช' },
  'nation-formation': { ms: 'Pembentukan Malaysia', en: 'Forming Malaysia', zh: '马来西亚的成立', ta: 'மலேசியாவின் உருவாக்கம்' , ja: 'マレーシアの成立', ko: '말레이시아의 형성', th: 'การก่อตั้งมาเลเซีย' },
  modern: { ms: 'Malaysia Moden', en: 'Modern Malaysia', zh: '现代马来西亚', ta: 'நவீன மலேசியா' , ja: '現代マレーシア', ko: '현대 말레이시아', th: 'มาเลเซียยุคใหม่' },
  identity: { ms: 'Identiti Nasional', en: 'National identity', zh: '国家认同', ta: 'தேசிய அடையாளம்' , ja: '国家アイデンティティ', ko: '국민 정체성', th: 'อัตลักษณ์ของชาติ' },

  // ---- arts & culture ----
  'performing-arts': { ms: 'Seni Persembahan', en: 'Performing arts', zh: '表演艺术', ta: 'நிகழ்த்துக் கலைகள்' , ja: '舞台芸術', ko: '공연 예술', th: 'ศิลปะการแสดง' },
  crafts: { ms: 'Kraf Tangan', en: 'Crafts', zh: '手工艺', ta: 'கைவினைப் பொருட்கள்' , ja: '工芸', ko: '공예', th: 'หัตถกรรม' },
  festivals: { ms: 'Perayaan', en: 'Festivals', zh: '节庆', ta: 'பண்டிகைகள்' , ja: '祭り', ko: '축제', th: 'เทศกาล' },
  languages: { ms: 'Bahasa', en: 'Languages', zh: '语言', ta: 'மொழிகள்' , ja: '言語', ko: '언어', th: 'ภาษา' },
  heritage: { ms: 'Warisan', en: 'Heritage', zh: '文化遗产', ta: 'பாரம்பரியம்' , ja: '文化遺産', ko: '문화유산', th: 'มรดกทางวัฒนธรรม' },

  // ---- law ----
  corporate: { ms: 'Korporat', en: 'Corporate', zh: '公司法', ta: 'நிறுவனம்' , ja: '会社法', ko: '회사법', th: 'กฎหมายบริษัท' },
  tax: { ms: 'Percukaian', en: 'Taxation', zh: '税务', ta: 'வரிவிதிப்பு' , ja: '税務', ko: '세무', th: 'ภาษีอากร' },
  employment: { ms: 'Pekerjaan', en: 'Employment', zh: '就业', ta: 'வேலைவாய்ப்பு' , ja: '雇用', ko: '고용', th: 'การจ้างงาน' },
  'legal-system': { ms: 'Sistem Perundangan', en: 'Legal system', zh: '法律体系', ta: 'சட்ட அமைப்பு' , ja: '法制度', ko: '법 체계', th: 'ระบบกฎหมาย' },
  'key-acts': { ms: 'Akta Utama', en: 'Key Acts', zh: '主要法令', ta: 'முக்கிய சட்டங்கள்' , ja: '主要な法令', ko: '주요 법령', th: 'พระราชบัญญัติสำคัญ' },
  // ---- glossary (civic terms) ----
  government: { ms: 'Kerajaan', en: 'Government', zh: '政府', ta: 'அரசாங்கம்' , ja: '政府', ko: '정부', th: 'รัฐบาล' },
  legal: { ms: 'Perundangan', en: 'Legal', zh: '法律', ta: 'சட்டம்' , ja: '法律', ko: '법률', th: 'กฎหมาย' },
  culture: { ms: 'Budaya', en: 'Culture', zh: '文化', ta: 'கலாச்சாரம்' , ja: '文化', ko: '문화', th: 'วัฒนธรรม' },
  constitutional: { ms: 'Perlembagaan', en: 'Constitutional', zh: '宪法', ta: 'அரசியலமைப்பு' , ja: '憲法', ko: '헌법', th: 'รัฐธรรมนูญ' },

  // ---- government ----
  agencies: { ms: 'Agensi', en: 'Agencies', zh: '机构', ta: 'முகமைகள்' , ja: '行政機関', ko: '행정 기관', th: 'หน่วยงาน' },
  institutions: { ms: 'Institusi', en: 'Institutions', zh: '体制机构', ta: 'நிறுவனங்கள்' , ja: '統治機構', ko: '통치 기구', th: 'สถาบันการปกครอง' },
  ministries: { ms: 'Kementerian', en: 'Ministries', zh: '部门', ta: 'அமைச்சுகள்' , ja: '省庁', ko: '부처', th: 'กระทรวง' },

  // ---- economy ----
  indicators: { ms: 'Petunjuk', en: 'Indicators', zh: '指标', ta: 'குறியீடுகள்' , ja: '指標', ko: '지표', th: 'ตัวชี้วัด' },
  sectors: { ms: 'Sektor', en: 'Sectors', zh: '行业领域', ta: 'துறைகள்' , ja: '産業分野', ko: '산업 분야', th: 'ภาคเศรษฐกิจ' },
  trade: { ms: 'Perdagangan', en: 'Trade', zh: '贸易', ta: 'வர்த்தகம்' , ja: '貿易', ko: '무역', th: 'การค้า' },
  'monetary-policy': { ms: 'Dasar Monetari', en: 'Monetary policy', zh: '货币政策', ta: 'நாணயக் கொள்கை' , ja: '金融政策', ko: '통화 정책', th: 'นโยบายการเงิน' },
  policy: { ms: 'Dasar', en: 'Policy', zh: '政策', ta: 'கொள்கை' , ja: '政策', ko: '정책', th: 'นโยบาย' },
  // `institutions` is already defined under government above — shared label.

  // ---- Phase 2: topic labels for newly-populated categories ----
  // agriculture
  beras: { ms: "Perdagangan Beras", en: "Rice trade", zh: "大米贸易", ta: "அரிசி வர்த்தகம்", ko: "쌀 무역", th: 'การค้าข้าว' },
  felda: { ms: "FELDA", en: "FELDA", zh: "联邦土地发展局 (FELDA)", ta: "FELDA", ko: "FELDA", th: 'FELDA' },
  'food-security': { ms: "Keterjaminan Makanan", en: "Food security", zh: "粮食安全", ta: "உணவுப் பாதுகாப்பு", ko: "식량 안보", th: 'ความมั่นคงทางอาหาร' },
  livestock: { ms: "Ternakan", en: "Livestock", zh: "畜牧业", ta: "கால்நடை வளர்ப்பு", ko: "축산업", th: 'ปศุสัตว์' },
  padi: { ms: "Padi", en: "Rice (padi)", zh: "稻米种植", ta: "நெல் (பாடி)", ko: "벼농사", th: 'ข้าวเปลือก (padi)' },
  'pekebun-kecil': { ms: "Pekebun Kecil", en: "Smallholders", zh: "小园主", ta: "சிறுதோட்டக்காரர்கள்", ko: "소농", th: 'เกษตรกรรายย่อย' },
  pemasaran: { ms: "Pemasaran Pertanian", en: "Agricultural marketing", zh: "农产品营销", ta: "வேளாண் சந்தைப்படுத்தல்", ko: "농산물 유통", th: 'การตลาดสินค้าเกษตร' },
  perikanan: { ms: "Perikanan", en: "Fisheries", zh: "渔业", ta: "மீன்வளம்", ko: "수산업", th: 'การประมง' },
  research: { ms: "Penyelidikan Pertanian", en: "Agricultural research", zh: "农业研究", ta: "வேளாண் ஆராய்ச்சி", ko: "농업 연구", th: 'การวิจัยด้านการเกษตร' },
  smallholders: { ms: "Pekebun Kecil", en: "Smallholders", zh: "小园主", ta: "சிறுதோட்டக்காரர்கள்", ko: "소농", th: 'เกษตรกรรายย่อย' },
  // agriculture/companies
  plantation: { ms: "Perladangan", en: "Plantations", zh: "种植园", ta: "தோட்டங்கள்", ko: "플랜테이션", th: 'สวนพืชเศรษฐกิจ' },
  // agriculture/food-lifestyle
  durian: { ms: "Durian & Buah Tropika", en: "Durian & tropical fruit", zh: "榴莲与热带水果", ta: "துரியான் & வெப்பமண்டல பழங்கள்", ko: "두리안 및 열대 과일", th: 'ทุเรียนและผลไม้เขตร้อน' },
  // arts-culture
  attire: { ms: "Pakaian Tradisional", en: "Traditional attire", zh: "传统服饰", ta: "பாரம்பரிய உடை", ko: "전통 의상", th: 'เครื่องแต่งกายดั้งเดิม' },
  film: { ms: "Filem", en: "Film", zh: "电影", ta: "திரைப்படம்", ko: "영화", th: 'ภาพยนตร์' },
  kebudayaan: { ms: "Dasar Kebudayaan", en: "Cultural policy", zh: "文化政策", ta: "கலாச்சாரக் கொள்கை", ko: "문화 정책", th: 'นโยบายวัฒนธรรม' },
  language: { ms: "Bahasa", en: "Language", zh: "语言", ta: "மொழி", ko: "언어", th: 'ภาษา' },
  'martial-arts': { ms: "Silat & Seni Bela Diri", en: "Martial arts", zh: "武术", ta: "தற்காப்புக் கலைகள்", ko: "무술", th: 'ศิลปะการต่อสู้' },
  music: { ms: "Muzik", en: "Music", zh: "音乐", ta: "இசை", ko: "음악", th: 'ดนตรี' },
  sastera: { ms: "Sastera", en: "Literature", zh: "文学", ta: "இலக்கியம்", ko: "문학", th: 'วรรณกรรม' },
  senibina: { ms: "Seni Bina", en: "Architecture", zh: "建筑", ta: "கட்டிடக்கலை", ko: "건축", th: 'สถาปัตยกรรม' },
  tarian: { ms: "Tarian Tradisional", en: "Traditional dance", zh: "传统舞蹈", ta: "பாரம்பரிய நடனம்", ko: "전통 무용", th: 'นาฏศิลป์ดั้งเดิม' },
  warisan: { ms: "Warisan", en: "Heritage", zh: "文化遗产", ta: "பாரம்பரியம்", ko: "문화유산", th: 'มรดกทางวัฒนธรรม' },
  // companies
  conglomerates: { ms: "Konglomerat", en: "Conglomerates", zh: "企业集团", ta: "கூட்டு நிறுவனங்கள்", ko: "복합기업", th: 'กลุ่มบริษัทขนาดใหญ่' },
  glc: { ms: "GLC & GLIC", en: "GLCs & GLICs", zh: "官联公司 (GLC)", ta: "GLC & GLIC", ko: "GLC 및 GLIC", th: 'บริษัทที่รัฐถือหุ้น (GLC และ GLIC)' },
  kewangan: { ms: "Kumpulan Kewangan", en: "Financial groups", zh: "金融集团", ta: "நிதிக் குழுமங்கள்", ko: "금융 그룹", th: 'กลุ่มธุรกิจการเงิน' },
  lebuhraya: { ms: "Lebuh Raya", en: "Highways", zh: "高速公路", ta: "நெடுஞ்சாலைகள்", ko: "고속도로", th: 'ทางหลวง' },
  pelaburan: { ms: "Dana Pelaburan", en: "Investment funds", zh: "投资基金", ta: "முதலீட்டு நிதிகள்", ko: "투자 펀드", th: 'กองทุนเพื่อการลงทุน' },
  pencen: { ms: "Dana Persaraan", en: "Retirement funds", zh: "退休基金", ta: "ஓய்வூதிய நிதிகள்", ko: "퇴직 기금", th: 'กองทุนเพื่อการเกษียณ' },
  pension: { ms: "Dana Pencen", en: "Pension funds", zh: "退休基金", ta: "ஓய்வூதிய நிதிகள்", ko: "연금 기금", th: 'กองทุนบำนาญ' },
  // companies/energy
  petroleum: { ms: "Petroleum", en: "Petroleum", zh: "石油", ta: "பெட்ரோலியம்", ko: "석유", th: 'ปิโตรเลียม' },
  utiliti: { ms: "Utiliti", en: "Utilities", zh: "公用事业", ta: "பயன்பாட்டு சேவைகள்", ko: "유틸리티", th: 'สาธารณูปโภค' },
  // companies/glossary
  'sovereign-wealth': { ms: "Dana Kekayaan Negara", en: "Sovereign wealth", zh: "主权财富基金", ta: "இறையாண்மைச் செல்வம்", ko: "국부펀드", th: 'กองทุนความมั่งคั่งแห่งชาติ' },
  // companies/industries
  manufacturing: { ms: "Pembuatan", en: "Manufacturing", zh: "制造业", ta: "உற்பத்தித் துறை", ko: "제조업", th: 'การผลิต' },
  // companies/technology
  telecoms: { ms: "Telekomunikasi", en: "Telecoms", zh: "电信", ta: "தொலைத்தொடர்பு", ko: "통신", th: 'โทรคมนาคม' },
  // energy
  elektrik: { ms: "Bekalan Elektrik", en: "Electricity supply", zh: "电力供应", ta: "மின்சார விநியோகம்", ko: "전력 공급", th: 'การจ่ายไฟฟ้า' },
  fuel: { ms: "Harga Bahan Api", en: "Fuel pricing", zh: "燃油定价", ta: "எரிபொருள் விலை", ko: "연료 가격", th: 'การกำหนดราคาน้ำมันเชื้อเพลิง' },
  gas: { ms: "Gas Asli & LNG", en: "Natural gas & LNG", zh: "天然气与液化天然气", ta: "இயற்கை எரிவாயு & LNG", ko: "천연가스 및 LNG", th: 'ก๊าซธรรมชาติและ LNG' },
  hydrogen: { ms: "Hidrogen & CCUS", en: "Hydrogen & CCUS", zh: "氢能与碳捕集", ta: "ஹைட்ரஜன் & CCUS", ko: "수소 및 CCUS", th: 'ไฮโดรเจนและ CCUS' },
  hydropower: { ms: "Hidrokuasa", en: "Hydropower", zh: "水力发电", ta: "நீர்மின்சக்தி", ko: "수력 발전", th: 'พลังงานน้ำ' },
  perundangan: { ms: "Perundangan Tenaga", en: "Energy legislation", zh: "能源立法", ta: "எரிசக்திச் சட்டம்", ko: "에너지 법령", th: 'กฎหมายพลังงาน' },
  reform: { ms: "Reformasi Tenaga", en: "Energy reform", zh: "能源改革", ta: "எரிசக்தி சீர்திருத்தம்", ko: "에너지 개혁", th: 'การปฏิรูปพลังงาน' },
  renewables: { ms: "Tenaga Boleh Baharu", en: "Renewables", zh: "可再生能源", ta: "புதுப்பிக்கத்தக்க எரிசக்தி", ko: "재생 에너지", th: 'พลังงานหมุนเวียน' },
  solar: { ms: "Tenaga Solar", en: "Solar power", zh: "太阳能", ta: "சூரிய சக்தி", ko: "태양광 발전", th: 'พลังงานแสงอาทิตย์' },
  subsidi: { ms: "Subsidi Bahan Api", en: "Fuel subsidies", zh: "燃油补贴", ta: "எரிபொருள் மானியங்கள்", ko: "연료 보조금", th: 'เงินอุดหนุนน้ำมันเชื้อเพลิง' },
  tarif: { ms: "Tarif Elektrik", en: "Electricity tariffs", zh: "电费费率", ta: "மின்சாரக் கட்டணங்கள்", ko: "전기 요금", th: 'อัตราค่าไฟฟ้า' },
  // energy/finance/glossary/technology
  regulator: { ms: "Pengawal Selia", en: "Regulators", zh: "监管机构", ta: "ஒழுங்குமுறை ஆணையங்கள்", ko: "규제 기관", th: 'หน่วยงานกำกับดูแล' },
  // environment
  'EIA': { ms: "Penilaian Impak Alam (EIA)", en: "Environmental impact (EIA)", zh: "环境影响评估 (EIA)", ta: "சுற்றுச்சூழல் தாக்க மதிப்பீடு (EIA)", ko: "환경영향평가(EIA)", th: 'การประเมินผลกระทบสิ่งแวดล้อม (EIA)' },
  carbon: { ms: "Pasaran Karbon", en: "Carbon market", zh: "碳市场", ta: "கார்பன் சந்தை", ko: "탄소 시장", th: 'ตลาดคาร์บอน' },
  climate: { ms: "Dasar Iklim", en: "Climate policy", zh: "气候政策", ta: "காலநிலைக் கொள்கை", ko: "기후 정책", th: 'นโยบายด้านสภาพภูมิอากาศ' },
  forests: { ms: "Penebangan Hutan", en: "Deforestation", zh: "森林砍伐", ta: "காடழிப்பு", ko: "삼림 벌채", th: 'การตัดไม้ทำลายป่า' },
  jerebu: { ms: "Jerebu", en: "Haze", zh: "烟霾", ta: "புகைமூட்டம்", ko: "연무", th: 'หมอกควัน' },
  land: { ms: "Tanah & Hak Adat", en: "Land & customary rights", zh: "土地与习俗权利", ta: "நிலம் & வழக்கமான உரிமைகள்", ko: "토지 및 관습적 권리", th: 'ที่ดินและสิทธิตามจารีตประเพณี' },
  pemuliharaan: { ms: "Pemuliharaan", en: "Conservation", zh: "自然保护", ta: "இயற்கைப் பாதுகாப்பு", ko: "자연 보전", th: 'การอนุรักษ์' },
  penyu: { ms: "Penyu & Pemuliharaan Marin", en: "Turtles & marine conservation", zh: "海龟与海洋保护", ta: "ஆமைகள் & கடல் பாதுகாப்பு", ko: "바다거북 및 해양 보전", th: 'เต่าทะเลและการอนุรักษ์ทางทะเล' },
  perhutanan: { ms: "Hutan Simpan", en: "Forest reserves", zh: "森林保护区", ta: "காப்புக் காடுகள்", ko: "보호림", th: 'ป่าสงวน' },
  plastik: { ms: "Pencemaran Plastik", en: "Plastic pollution", zh: "塑料污染", ta: "பிளாஸ்டிக் மாசு", ko: "플라스틱 오염", th: 'มลพิษจากพลาสติก' },
  pollution: { ms: "Undang-Undang Alam Sekitar", en: "Environmental law", zh: "环境法", ta: "சுற்றுச்சூழல் சட்டம்", ko: "환경법", th: 'กฎหมายสิ่งแวดล้อม' },
  udara: { ms: "Kualiti Udara", en: "Air quality", zh: "空气质量", ta: "காற்றின் தரம்", ko: "대기질", th: 'คุณภาพอากาศ' },
  waste: { ms: "Pengurusan Sisa", en: "Waste management", zh: "废物管理", ta: "கழிவு மேலாண்மை", ko: "폐기물 관리", th: 'การจัดการขยะ' },
  water: { ms: "Keselamatan Air", en: "Water security", zh: "水资源安全", ta: "நீர்ப் பாதுகாப்பு", ko: "수자원 안보", th: 'ความมั่นคงด้านน้ำ' },
  wildlife: { ms: "Hidupan Liar", en: "Wildlife", zh: "野生动物", ta: "வனவிலங்குகள்", ko: "야생동물", th: 'สัตว์ป่า' },
  // environment/industries
  'palm-oil': { ms: "Minyak Sawit", en: "Palm oil", zh: "棕榈油", ta: "பாமாயில்", ko: "팜유", th: 'น้ำมันปาล์ม' },
  // finance
  bonds: { ms: "Pasaran Bon", en: "Bond market", zh: "债券市场", ta: "பத்திரச் சந்தை", ko: "채권 시장", th: 'ตลาดตราสารหนี้' },
  'capital-markets': { ms: "Pasaran Modal", en: "Capital markets", zh: "资本市场", ta: "மூலதனச் சந்தைகள்", ko: "자본 시장", th: 'ตลาดทุน' },
  credit: { ms: "Laporan Kredit", en: "Credit reporting", zh: "信用报告", ta: "கடன் அறிக்கையிடல்", ko: "신용 정보", th: 'การรายงานข้อมูลเครดิต' },
  fintech: { ms: "Fintech", en: "Fintech", zh: "金融科技", ta: "ஃபின்டெக்", ko: "핀테크", th: 'ฟินเทค' },
  investing: { ms: "Pelaburan", en: "Investing", zh: "投资", ta: "முதலீடு", ko: "투자", th: 'การลงทุน' },
  lending: { ms: "Pembiayaan & Pinjaman", en: "Lending & financing", zh: "贷款与融资", ta: "கடன் & நிதியுதவி", ko: "대출 및 자금 조달", th: 'การให้สินเชื่อและการจัดหาเงินทุน' },
  payments: { ms: "Sistem Pembayaran", en: "Payments", zh: "支付系统", ta: "கட்டணங்கள்", ko: "결제", th: 'ระบบการชำระเงิน' },
  retirement: { ms: "Simpanan Persaraan", en: "Retirement savings", zh: "退休储蓄", ta: "ஓய்வுக்காலச் சேமிப்பு", ko: "퇴직 저축", th: 'เงินออมเพื่อการเกษียณ' },
  takaful: { ms: "Takaful & Insurans", en: "Takaful & insurance", zh: "伊斯兰保险与保险", ta: "தகாஃபுல் & காப்பீடு", ko: "타카풀 및 보험", th: 'ตะกาฟุลและการประกันภัย' },
  // food-lifestyle
  alcohol: { ms: "Peraturan Alkohol", en: "Alcohol rules", zh: "酒类法规", ta: "மது விதிகள்", ko: "주류 규정", th: 'กฎระเบียบเกี่ยวกับเครื่องดื่มแอลกอฮอล์' },
  cuisine: { ms: "Juadah Perayaan", en: "Festive cuisine", zh: "节庆美食", ta: "பண்டிகை உணவு", ko: "명절 음식", th: 'อาหารในเทศกาล' },
  dining: { ms: "Pilihan Pemakanan", en: "Dietary dining", zh: "饮食选择", ta: "உணவுமுறை சார்ந்த உணவகம்", ko: "식단별 외식", th: 'ทางเลือกอาหารเฉพาะ' },
  hiburan: { ms: "Hiburan", en: "Entertainment", zh: "娱乐", ta: "பொழுதுபோக்கு", ko: "엔터테인먼트", th: 'ความบันเทิง' },
  kopitiam: { ms: "Budaya Kopitiam", en: "Kopitiam culture", zh: "咖啡店文化", ta: "கோபிதியாம் கலாச்சாரம்", ko: "코피티암 문화", th: 'วัฒนธรรมโกปี๊เตี๊ยม (kopitiam)' },
  makanan: { ms: "Hidangan Kebangsaan", en: "National dishes", zh: "国民美食", ta: "தேசிய உணவுகள்", ko: "대표 음식", th: 'อาหารประจำชาติ' },
  masakan: { ms: "Masakan Serantau", en: "Regional cuisine", zh: "地方菜系", ta: "பிராந்திய உணவுகள்", ko: "지역 요리", th: 'อาหารประจำภูมิภาค' },
  pasar: { ms: "Pasar Rakyat", en: "Markets & street food", zh: "市集与街头美食", ta: "சந்தைகள் & தெரு உணவு", ko: "시장 및 길거리 음식", th: 'ตลาดและอาหารริมทาง' },
  ramadan: { ms: "Bazar Ramadan", en: "Ramadan bazaars", zh: "斋月市集", ta: "ரமலான் பஜார்கள்", ko: "라마단 바자르", th: 'ตลาดนัดรอมฎอน (Ramadan)' },
  retail: { ms: "Runcit & Beli-belah", en: "Retail & shopping", zh: "零售与购物", ta: "சில்லறை & ஷாப்பிங்", ko: "소매 및 쇼핑", th: 'การค้าปลีกและการช้อปปิ้ง' },
  // food-lifestyle/glossary/industries
  halal: { ms: "Halal", en: "Halal", zh: "清真认证", ta: "ஹலால்", ko: "할랄", th: 'ฮาลาล' },
  // glossary
  kenegaraan: { ms: "Kenegaraan", en: "Nationhood", zh: "国家理念", ta: "தேசியம்", ko: "국가성", th: 'ความเป็นชาติ' },
  kerajaan: { ms: "Kerajaan", en: "Government", zh: "政府", ta: "அரசாங்கம்", ko: "정부", th: 'รัฐบาล' },
  peribumi: { ms: "Orang Asli", en: "Indigenous Peoples", zh: "原住民", ta: "பழங்குடி மக்கள்", ko: "원주민", th: 'ชนพื้นเมือง (Orang Asli)' },
  tanah: { ms: "Tanah", en: "Land", zh: "土地", ta: "நிலம்", ko: "토지", th: 'ที่ดิน' },
  zakat: { ms: "Zakat", en: "Zakat", zh: "天课 (Zakat)", ta: "ஜகாத் (Zakat)", ko: "자카트(Zakat)", th: 'ซะกาต (Zakat)' },
  // glossary/government
  monarki: { ms: "Institusi Diraja", en: "Monarchy", zh: "王室", ta: "முடியாட்சி", ko: "군주제", th: 'สถาบันพระมหากษัตริย์' },
  // glossary/industries
  economy: { ms: "Ekonomi", en: "Economy", zh: "经济", ta: "பொருளாதாரம்", ko: "경제", th: 'เศรษฐกิจ' },
  // glossary/public-safety
  polis: { ms: "Polis", en: "Police", zh: "警察", ta: "காவல்துறை", ko: "경찰", th: 'ตำรวจ' },
  // government
  autonomi: { ms: "Autonomi Sabah & Sarawak", en: "Sabah & Sarawak autonomy", zh: "沙巴与砂拉越自治", ta: "சபா & சரவாக் சுயாட்சி", ko: "사바·사라왁 자치", th: 'การปกครองตนเองของซาบาห์และซาราวัก (Sabah & Sarawak)' },
  'central-bank': { ms: "Bank Pusat", en: "Central bank", zh: "中央银行", ta: "மத்திய வங்கி", ko: "중앙은행", th: 'ธนาคารกลาง' },
  citizenship: { ms: "Kewarganegaraan", en: "Citizenship", zh: "公民权", ta: "குடியுரிமை", ko: "시민권", th: 'สัญชาติ' },
  constitution: { ms: "Perlembagaan", en: "Constitution", zh: "宪法", ta: "அரசியலமைப்பு", ko: "헌법", th: 'รัฐธรรมนูญ' },
  kehakiman: { ms: "Kehakiman", en: "Judiciary", zh: "司法", ta: "நீதித்துறை", ko: "사법부", th: 'ฝ่ายตุลาการ' },
  parties: { ms: "Parti Politik", en: "Political parties", zh: "政党", ta: "அரசியல் கட்சிகள்", ko: "정당", th: 'พรรคการเมือง' },
  pertahanan: { ms: "Pertahanan", en: "Defence", zh: "国防", ta: "பாதுகாப்பு", ko: "국방", th: 'การป้องกันประเทศ' },
  transparency: { ms: "Ketelusan", en: "Transparency", zh: "政府透明度", ta: "வெளிப்படைத்தன்மை", ko: "투명성", th: 'ความโปร่งใส' },
  treasury: { ms: "Perbendaharaan", en: "Treasury", zh: "财政部", ta: "கருவூலம்", ko: "재무부", th: 'กระทรวงการคลัง' },
  // government/international
  diplomacy: { ms: "Diplomasi", en: "Diplomacy", zh: "外交", ta: "இராஜதந்திரம்", ko: "외교", th: 'การทูต' },
  // government/public-safety
  keselamatan: { ms: "Keselamatan Negara", en: "National security", zh: "国家安全", ta: "தேசியப் பாதுகாப்பு", ko: "국가 안보", th: 'ความมั่นคงแห่งชาติ' },
  // healthcare
  darah: { ms: "Pendermaan Darah", en: "Blood donation", zh: "献血", ta: "இரத்த தானம்", ko: "헌혈", th: 'การบริจาคโลหิต' },
  'digital-health': { ms: "Kesihatan Digital", en: "Digital health", zh: "数字医疗", ta: "டிஜிட்டல் சுகாதாரம்", ko: "디지털 헬스", th: 'สุขภาพดิจิทัล' },
  disability: { ms: "OKU & Kesihatan", en: "Disability & health", zh: "残障与健康", ta: "ஊனம் & சுகாதாரம்", ko: "장애 및 건강", th: 'ความพิการและสุขภาพ' },
  hiv: { ms: "HIV & Kesihatan Seksual", en: "HIV & sexual health", zh: "艾滋病与性健康", ta: "HIV & பாலியல் சுகாதாரம்", ko: "HIV 및 성 건강", th: 'HIV และสุขภาพทางเพศ' },
  ncd: { ms: "Penyakit Tidak Berjangkit", en: "Noncommunicable diseases", zh: "非传染性疾病", ta: "தொற்றா நோய்கள்", ko: "비전염성 질환", th: 'โรคไม่ติดต่อ' },
  paliatif: { ms: "Penjagaan Paliatif", en: "Palliative care", zh: "缓和医疗", ta: "நோய்த்தணிப்பு பராமரிப்பு", ko: "완화 의료", th: 'การดูแลแบบประคับประคอง' },
  pandemik: { ms: "Pandemik", en: "Pandemics", zh: "疫情", ta: "கொள்ளைநோய்கள்", ko: "팬데믹", th: 'โรคระบาดใหญ่' },
  pendaftaran: { ms: "Pendaftaran Profesional", en: "Professional registration", zh: "专业注册", ta: "தொழில்முறை பதிவு", ko: "전문가 등록", th: 'การขึ้นทะเบียนวิชาชีพ' },
  pengguguran: { ms: "Pengguguran", en: "Abortion", zh: "堕胎", ta: "கருக்கலைப்பு", ko: "임신중절", th: 'การทำแท้ง' },
  reformasi: { ms: "Reformasi Kesihatan", en: "Health reform", zh: "医疗改革", ta: "சுகாதார சீர்திருத்தம்", ko: "의료 개혁", th: 'การปฏิรูประบบสุขภาพ' },
  telemedicine: { ms: "Teleperubatan", en: "Telemedicine", zh: "远程医疗", ta: "தொலைமருத்துவம்", ko: "원격 의료", th: 'การแพทย์ทางไกล' },
  tembakau: { ms: "Kawalan Tembakau", en: "Tobacco control", zh: "烟草管制", ta: "புகையிலைக் கட்டுப்பாடு", ko: "담배 규제", th: 'การควบคุมยาสูบ' },
  transplan: { ms: "Pendermaan Organ", en: "Organ donation", zh: "器官捐赠", ta: "உறுப்பு தானம்", ko: "장기 기증", th: 'การบริจาคอวัยวะ' },
  vaksin: { ms: "Vaksin", en: "Vaccines", zh: "疫苗", ta: "தடுப்பூசிகள்", ko: "백신", th: 'วัคซีน' },
  // industries
  aerospace: { ms: "Aeroangkasa & MRO", en: "Aerospace & MRO", zh: "航空航天与维修", ta: "வான்வெளி & MRO", ko: "항공우주 및 MRO", th: 'อากาศยานและ MRO' },
  automotive: { ms: "Automotif", en: "Automotive", zh: "汽车业", ta: "வாகனத் துறை", ko: "자동차 산업", th: 'ยานยนต์' },
  bumiputera: { ms: "Ekuiti Bumiputera", en: "Bumiputera equity", zh: "土著股权", ta: "பூமிபுத்ரா பங்கு", ko: "부미푸트라 지분", th: 'หุ้นภูมิบุตร (Bumiputera)' },
  construction: { ms: "Pembinaan", en: "Construction", zh: "建筑业", ta: "கட்டுமானத் துறை", ko: "건설업", th: 'การก่อสร้าง' },
  energy: { ms: "Minyak & Gas", en: "Oil & gas", zh: "石油与天然气", ta: "எண்ணெய் & எரிவாயு", ko: "석유 및 가스", th: 'น้ำมันและก๊าซ' },
  logistics: { ms: "Logistik & Pelabuhan", en: "Logistics & ports", zh: "物流与港口", ta: "தளவாடம் & துறைமுகங்கள்", ko: "물류 및 항만", th: 'โลจิสติกส์และท่าเรือ' },
  rubber: { ms: "Industri Getah", en: "Rubber industry", zh: "橡胶业", ta: "ரப்பர் தொழில்", ko: "고무 산업", th: 'อุตสาหกรรมยางพารา' },
  semiconductors: { ms: "Semikonduktor", en: "Semiconductors", zh: "半导体", ta: "அரைக்கடத்திகள்", ko: "반도체", th: 'เซมิคอนดักเตอร์' },
  // industries/technology
  datacentres: { ms: "Pusat Data", en: "Data centres", zh: "数据中心", ta: "தரவு மையங்கள்", ko: "데이터 센터", th: 'ศูนย์ข้อมูล' },
  digital: { ms: "Ekonomi Digital", en: "Digital economy", zh: "数字经济", ta: "டிஜிட்டல் பொருளாதாரம்", ko: "디지털 경제", th: 'เศรษฐกิจดิจิทัล' },
  // international
  asean: { ms: "ASEAN", en: "ASEAN", zh: "东盟 (ASEAN)", ta: "ASEAN", ko: "ASEAN", th: 'ASEAN' },
  bilateral: { ms: "Hubungan Dwihala", en: "Bilateral relations", zh: "双边关系", ta: "இருதரப்பு உறவுகள்", ko: "양자 관계", th: 'ความสัมพันธ์ทวิภาคี' },
  diplomasi: { ms: "Hubungan Serantau", en: "Regional relations", zh: "区域关系", ta: "பிராந்திய உறவுகள்", ko: "역내 관계", th: 'ความสัมพันธ์ระดับภูมิภาค' },
  singapore: { ms: "Singapura", en: "Singapore", zh: "新加坡", ta: "சிங்கப்பூர்", ko: "싱가포르", th: 'สิงคโปร์ (Singapore)' },
  // international/public-safety
  maritim: { ms: "Pertikaian Maritim", en: "Maritime disputes", zh: "海事争端", ta: "கடல்சார் தகராறுகள்", ko: "해양 분쟁", th: 'ข้อพิพาททางทะเล' },
  // malaysia
  'country-basics': { ms: "Asas Negara", en: "Country basics", zh: "国家概况", ta: "நாட்டு அடிப்படைகள்", ko: "국가 개요", th: 'ข้อมูลพื้นฐานของประเทศ' },
  demographics: { ms: "Demografi", en: "Demographics", zh: "人口结构", ta: "மக்கள்தொகையியல்", ko: "인구 구성", th: 'ประชากรศาสตร์' },
  geography: { ms: "Geografi", en: "Geography", zh: "地理", ta: "புவியியல்", ko: "지리", th: 'ภูมิศาสตร์' },
  // public-safety
  banjir: { ms: "Banjir", en: "Floods", zh: "水灾", ta: "வெள்ளம்", ko: "홍수", th: 'อุทกภัย' },
  bencana: { ms: "Pengurusan Bencana", en: "Disaster management", zh: "灾害管理", ta: "பேரிடர் மேலாண்மை", ko: "재난 관리", th: 'การจัดการภัยพิบัติ' },
  kebakaran: { ms: "Keselamatan Kebakaran", en: "Fire safety", zh: "消防安全", ta: "தீ பாதுகாப்பு", ko: "소방 안전", th: 'ความปลอดภัยด้านอัคคีภัย' },
  kecemasan: { ms: "Perkhidmatan Kecemasan", en: "Emergency services", zh: "紧急服务", ta: "அவசர சேவைகள்", ko: "긴급 서비스", th: 'บริการฉุกเฉิน' },
  komuniti: { ms: "Keselamatan Komuniti", en: "Community safety", zh: "社区安全", ta: "சமூகப் பாதுகாப்பு", ko: "지역사회 안전", th: 'ความปลอดภัยในชุมชน' },
  penipuan: { ms: "Penipuan & Jenayah Kewangan", en: "Scams & financial crime", zh: "诈骗与金融犯罪", ta: "மோசடிகள் & நிதிக் குற்றம்", ko: "사기 및 금융 범죄", th: 'การหลอกลวงและอาชญากรรมทางการเงิน' },
  'pertahanan-diri': { ms: "Pertahanan Diri", en: "Self-defence", zh: "自卫", ta: "தற்காப்பு", ko: "자기방어", th: 'การป้องกันตัว' },
  policing: { ms: "Kepolisan", en: "Policing", zh: "警务", ta: "காவல் பணி", ko: "치안 활동", th: 'การปฏิบัติงานของตำรวจ' },
  rela: { ms: "RELA", en: "RELA", zh: "人民志愿警卫队 (RELA)", ta: "RELA", ko: "RELA", th: 'RELA' },
  traffic: { ms: "Keselamatan Jalan Raya", en: "Road safety", zh: "道路安全", ta: "சாலைப் பாதுகாப்பு", ko: "도로 안전", th: 'ความปลอดภัยบนท้องถนน' },
  // sports
  badminton: { ms: "Badminton", en: "Badminton", zh: "羽毛球", ta: "பூப்பந்து", ko: "배드민턴", th: 'แบดมินตัน' },
  bolasepak: { ms: "Liga Bola Sepak", en: "Football leagues", zh: "足球联赛", ta: "கால்பந்து லீக்குகள்", ko: "축구 리그", th: 'ลีกฟุตบอล' },
  cycling: { ms: "Lumba Basikal", en: "Cycling", zh: "自行车运动", ta: "மிதிவண்டி பந்தயம்", ko: "사이클링", th: 'จักรยาน' },
  football: { ms: "Bola Sepak", en: "Football", zh: "足球", ta: "கால்பந்து", ko: "축구", th: 'ฟุตบอล' },
  hoki: { ms: "Hoki", en: "Hockey", zh: "曲棍球", ta: "ஹாக்கி", ko: "하키", th: 'ฮอกกี้' },
  integriti: { ms: "Integriti Sukan", en: "Sports integrity", zh: "体育诚信", ta: "விளையாட்டு நேர்மை", ko: "스포츠 공정성", th: 'ความสุจริตในวงการกีฬา' },
  medals: { ms: "Rekod Pingat", en: "Medal record", zh: "奖牌纪录", ta: "பதக்கச் சாதனை", ko: "메달 기록", th: 'สถิติเหรียญรางวัล' },
  motorsport: { ms: "Sukan Motor", en: "Motorsport", zh: "赛车运动", ta: "மோட்டார் விளையாட்டு", ko: "모터스포츠", th: 'มอเตอร์สปอร์ต' },
  naturalisasi: { ms: "Naturalisasi Sukan", en: "Sports naturalisation", zh: "体育归化", ta: "விளையாட்டு குடியுரிமை வழங்கல்", ko: "스포츠 귀화", th: 'การโอนสัญชาตินักกีฬา' },
  paralimpik: { ms: "Paralimpik", en: "Paralympics", zh: "残奥会", ta: "பாராலிம்பிக்", ko: "패럴림픽", th: 'พาราลิมปิก' },
  participation: { ms: "Penyertaan Sukan", en: "Sports participation", zh: "体育参与", ta: "விளையாட்டுப் பங்கேற்பு", ko: "스포츠 참여", th: 'การมีส่วนร่วมในกีฬา' },
  squash: { ms: "Skuasy", en: "Squash", zh: "壁球", ta: "ஸ்குவாஷ்", ko: "스쿼시", th: 'สควอช' },
  sukma: { ms: "SUKMA", en: "SUKMA", zh: "马来西亚运动会 (SUKMA)", ta: "SUKMA", ko: "SUKMA", th: 'SUKMA' },
  takraw: { ms: "Sepak Takraw", en: "Sepak takraw", zh: "藤球", ta: "செபாக் தக்ரா", ko: "세팍타크로", th: 'เซปักตะกร้อ' },
  venue: { ms: "Gelanggang Sukan", en: "Sports venues", zh: "体育场馆", ta: "விளையாட்டு அரங்குகள்", ko: "스포츠 경기장", th: 'สนามกีฬา' },
  // technology
  cybersecurity: { ms: "Keselamatan Siber", en: "Cybersecurity", zh: "网络安全", ta: "இணையப் பாதுகாப்பு", ko: "사이버 보안", th: 'ความมั่นคงปลอดภัยไซเบอร์' },
  dasar: { ms: "Dasar Digital", en: "Digital policy", zh: "数字政策", ta: "டிஜிட்டல் கொள்கை", ko: "디지털 정책", th: 'นโยบายดิจิทัล' },
  'digital-identity': { ms: "Identiti Digital", en: "Digital identity", zh: "数字身份", ta: "டிஜிட்டல் அடையாளம்", ko: "디지털 신원", th: 'อัตลักษณ์ดิจิทัล' },
  kementerian: { ms: "Kementerian Digital", en: "Digital ministry", zh: "数字部", ta: "டிஜிட்டல் அமைச்சு", ko: "디지털부", th: 'กระทรวงดิจิทัล' },
  startups: { ms: "Ekosistem Startup", en: "Startups", zh: "创业生态", ta: "தொடக்க நிறுவனங்கள்", ko: "스타트업", th: 'สตาร์ทอัพ' },
  // tourism
  destinations: { ms: "Destinasi", en: "Destinations", zh: "旅游目的地", ta: "சுற்றுலா தலங்கள்", ko: "여행지", th: 'จุดหมายปลายทาง' },
  diving: { ms: "Menyelam & Ekopelancongan Marin", en: "Diving & marine ecotourism", zh: "潜水与海洋生态旅游", ta: "நீர்மூழ்கல் & கடல் சுற்றுச்சூழல் சுற்றுலா", ko: "다이빙 및 해양 생태관광", th: 'การดำน้ำและการท่องเที่ยวเชิงนิเวศทางทะเล' },
  events: { ms: "MICE & Acara", en: "MICE & events", zh: "会展旅游", ta: "MICE & நிகழ்வுகள்", ko: "MICE 및 행사", th: 'MICE และงานอีเวนต์' },
  healthcare: { ms: "Pelancongan Perubatan", en: "Medical tourism", zh: "医疗旅游", ta: "மருத்துவ சுற்றுலா", ko: "의료 관광", th: 'การท่องเที่ยวเชิงการแพทย์' },
  highlands: { ms: "Tanah Tinggi", en: "Highlands", zh: "高原地区", ta: "மலைப்பகுதிகள்", ko: "고원 지대", th: 'พื้นที่สูง' },
  islands: { ms: "Pulau", en: "Islands", zh: "海岛", ta: "தீவுகள்", ko: "섬", th: 'เกาะ' },
  kualalumpur: { ms: "Kuala Lumpur", en: "Kuala Lumpur", zh: "吉隆坡", ta: "கோலாலம்பூர்", ko: "쿠알라룸푸르", th: 'กัวลาลัมเปอร์ (Kuala Lumpur)' },
  langkawi: { ms: "Langkawi", en: "Langkawi", zh: "兰卡威", ta: "லங்காவி", ko: "랑카위", th: 'ลังกาวี (Langkawi)' },
  planning: { ms: "Tip Perancangan", en: "Trip planning", zh: "行程规划", ta: "பயணத் திட்டமிடல்", ko: "여행 계획", th: 'การวางแผนการเดินทาง' },
  rainforest: { ms: "Hutan Hujan", en: "Rainforest", zh: "雨林", ta: "மழைக்காடு", ko: "열대우림", th: 'ป่าฝน' },
  sabah: { ms: "Sabah", en: "Sabah", zh: "沙巴", ta: "சபா", ko: "사바", th: 'ซาบาห์ (Sabah)' },
  sarawak: { ms: "Sarawak", en: "Sarawak", zh: "砂拉越", ta: "சரவாக்", ko: "사라왁", th: 'ซาราวัก (Sarawak)' },
  transport: { ms: "Pengangkutan", en: "Getting around", zh: "交通出行", ta: "போக்குவரத்து", ko: "교통 이용", th: 'การเดินทางในประเทศ' },
  visa: { ms: "Syarat Kemasukan", en: "Entry requirements", zh: "入境要求", ta: "நுழைவுத் தேவைகள்", ko: "입국 요건", th: 'ข้อกำหนดการเข้าเมือง' },
  // ---- auto-filled: subcategory keys used by articles but previously unlabelled
  //      (fell back to the raw slug on every locale). Trilingual labels added.
  accreditation: { ms: "Akreditasi", en: "Accreditation", zh: "学历认证", ta: "அங்கீகாரம்", ko: "학력 인증", th: 'การรับรองวิทยฐานะ' },
  agama: { ms: "Pendidikan Agama", en: "Religious education", zh: "宗教教育", ta: "மத கல்வி", ko: "종교 교육", th: 'การศึกษาศาสนา' },
  amalgamation: { ms: "Penggabungan Syarikat", en: "Amalgamation", zh: "公司合并", ta: "நிறுவன இணைப்பு", ko: "회사 합병", th: 'การควบรวมบริษัท' },
  'anti-corruption': { ms: "Antirasuah", en: "Anti-corruption", zh: "反贪腐", ta: "ஊழல் எதிர்ப்பு", ko: "반부패", th: 'การต่อต้านการทุจริต' },
  arbitration: { ms: "Timbang Tara", en: "Arbitration", zh: "仲裁", ta: "நடுவர் தீர்ப்பு", ko: "중재", th: 'อนุญาโตตุลาการ' },
  assurance: { ms: "Jaminan Audit", en: "Assurance", zh: "鉴证", ta: "உறுதிப்படுத்தல்", ko: "인증 업무", th: 'งานให้ความเชื่อมั่น' },
  auction: { ms: "Lelongan", en: "Auctions", zh: "拍卖", ta: "ஏலம்", ko: "경매", th: 'การประมูล' },
  audit: { ms: "Audit", en: "Audit", zh: "审计", ta: "தணிக்கை", ko: "감사", th: 'การตรวจสอบบัญชี' },
  auditor: { ms: "Juruaudit", en: "Auditors", zh: "审计师", ta: "தணிக்கையாளர்கள்", ko: "감사인", th: 'ผู้สอบบัญชี' },
  'bantuan-guaman': { ms: "Bantuan Guaman", en: "Legal aid", zh: "法律援助", ta: "சட்ட உதவி", ko: "법률 구조", th: 'ความช่วยเหลือทางกฎหมาย' },
  belanjawan: { ms: "Belanjawan Isi Rumah", en: "Household budgeting", zh: "家庭预算", ta: "குடும்ப பட்ஜெட்", ko: "가계 예산", th: 'การจัดทำงบประมาณครัวเรือน' },
  biasiswa: { ms: "Biasiswa", en: "Scholarships", zh: "奖学金", ta: "புலமைப்பரிசில்கள்", ko: "장학금", th: 'ทุนการศึกษา' },
  boarding: { ms: "Sekolah Berasrama", en: "Boarding schools", zh: "寄宿学校", ta: "தங்கும் விடுதிப் பள்ளிகள்", ko: "기숙학교", th: 'โรงเรียนประจำ' },
  buruh: { ms: "Undang-Undang Buruh", en: "Labour law", zh: "劳工法", ta: "தொழிலாளர் சட்டம்", ko: "노동법", th: 'กฎหมายแรงงาน' },
  buses: { ms: "Perkhidmatan Bas", en: "Buses", zh: "巴士", ta: "பேருந்துகள்", ko: "버스", th: 'รถโดยสารประจำทาง' },
  competition: { ms: "Persaingan", en: "Competition", zh: "竞争法", ta: "போட்டி", ko: "경쟁법", th: 'กฎหมายการแข่งขันทางการค้า' },
  compliance: { ms: "Pematuhan", en: "Compliance", zh: "合规", ta: "இணக்கம்", ko: "법규 준수", th: 'การปฏิบัติตามกฎระเบียบ' },
  consolidation: { ms: "Penyata Disatukan", en: "Consolidation", zh: "合并报表", ta: "ஒருங்கிணைந்த கணக்குகள்", ko: "연결 재무제표", th: 'งบการเงินรวม' },
  conversion: { ms: "Penukaran Status", en: "Conversion", zh: "公司转型", ta: "நிலை மாற்றம்", ko: "회사 전환", th: 'การแปรสภาพบริษัท' },
  cukai: { ms: "Percukaian", en: "Taxation", zh: "税务", ta: "வரிவிதிப்பு", ko: "세무", th: 'ภาษีอากร' },
  currency: { ms: "Mata Wang", en: "Currency", zh: "货币", ta: "நாணயம்", ko: "통화", th: 'สกุลเงิน' },
  customs: { ms: "Duti Kastam", en: "Customs duty", zh: "关税", ta: "சுங்க வரி", ko: "관세", th: 'อากรศุลกากร' },
  daerah: { ms: "Pentadbiran Daerah", en: "District administration", zh: "县级行政", ta: "மாவட்ட நிர்வாகம்", ko: "군(district) 행정", th: 'การบริหารระดับอำเภอ' },
  'digital-assets': { ms: "Aset Digital", en: "Digital assets", zh: "数字资产", ta: "டிஜிட்டல் சொத்துகள்", ko: "디지털 자산", th: 'สินทรัพย์ดิจิทัล' },
  disclosure: { ms: "Pendedahan", en: "Disclosures", zh: "披露", ta: "வெளிப்பாடுகள்", ko: "공시", th: 'การเปิดเผยข้อมูล' },
  divorce: { ms: "Perceraian", en: "Divorce", zh: "离婚", ta: "விவாகரத்து", ko: "이혼", th: 'การหย่าร้าง' },
  egumis: { ms: "Wang Tak Dituntut", en: "Unclaimed money", zh: "无人认领款项", ta: "உரிமை கோராத பணம்", ko: "미청구 자금", th: 'เงินที่ไม่มีผู้รับ' },
  ejen: { ms: "Ejen Hartanah", en: "Property agents", zh: "房地产中介", ta: "சொத்து முகவர்கள்", ko: "부동산 중개인", th: 'ตัวแทนอสังหาริมทรัพย์' },
  environment: { ms: "Alam Sekitar", en: "Environmental law", zh: "环境法", ta: "சுற்றுச்சூழல் சட்டம்", ko: "환경법", th: 'กฎหมายสิ่งแวดล้อม' },
  estate: { ms: "Cukai Warisan", en: "Estate & inheritance tax", zh: "遗产税", ta: "சொத்து & வாரிசு வரி", ko: "상속세", th: 'ภาษีมรดก' },
  ev: { ms: "Kenderaan Elektrik", en: "Electric vehicles", zh: "电动车", ta: "மின்சார வாகனங்கள்", ko: "전기차", th: 'ยานยนต์ไฟฟ้า' },
  ewallet: { ms: "E-Dompet", en: "E-wallets", zh: "电子钱包", ta: "மின் பணப்பைகள்", ko: "전자지갑", th: 'กระเป๋าเงินอิเล็กทรอนิกส์' },
  excise: { ms: "Duti Eksais", en: "Excise duty", zh: "国产税", ta: "கலால் வரி", ko: "물품세", th: 'ภาษีสรรพสามิต' },
  ferries: { ms: "Feri", en: "Ferries", zh: "渡轮", ta: "படகுகள்", ko: "페리", th: 'เรือข้ามฟาก' },
  'financial-regulation': { ms: "Pengawalan Kewangan", en: "Financial regulation", zh: "金融监管", ta: "நிதி ஒழுங்குமுறை", ko: "금융 규제", th: 'การกำกับดูแลภาคการเงิน' },
  'fisheries-governance': { ms: "Tadbir Urus Perikanan", en: "Fisheries governance", zh: "渔业管理", ta: "மீன்வள மேலாண்மை", ko: "수산업 관리", th: 'การกำกับดูแลการประมง' },
  fiskal: { ms: "Kewangan Negeri", en: "State finances", zh: "州财政", ta: "மாநில நிதி", ko: "주 재정", th: 'การคลังของรัฐ' },
  foreign: { ms: "Syarikat Asing", en: "Foreign companies", zh: "外国公司", ta: "வெளிநாட்டு நிறுவனங்கள்", ko: "외국 기업", th: 'บริษัทต่างชาติ' },
  franchise: { ms: "Francais", en: "Franchising", zh: "特许经营", ta: "உரிமையாக்கம்", ko: "프랜차이즈", th: 'แฟรนไชส์' },
  gaji: { ms: "Gaji & Potongan", en: "Wages", zh: "薪资", ta: "ஊதியம்", ko: "임금", th: 'ค่าจ้าง' },
  gig: { ms: "Pekerja Gig", en: "Gig workers", zh: "零工工作者", ta: "கிக் தொழிலாளர்கள்", ko: "긱 워커", th: 'แรงงานกิ๊ก' },
  'hak-asasi': { ms: "Hak Asasi Manusia", en: "Human rights", zh: "人权", ta: "மனித உரிமைகள்", ko: "인권", th: 'สิทธิมนุษยชน' },
  history: { ms: "Sejarah", en: "History", zh: "历史", ta: "வரலாறு", ko: "역사", th: 'ประวัติศาสตร์' },
  homebuyer: { ms: "Perlindungan Pembeli Rumah", en: "Homebuyer protection", zh: "购房者保护", ta: "வீடு வாங்குவோர் பாதுகாப்பு", ko: "주택 구매자 보호", th: 'การคุ้มครองผู้ซื้อบ้าน' },
  hutang: { ms: "Hutang", en: "Debt", zh: "债务", ta: "கடன்", ko: "부채", th: 'หนี้สิน' },
  imigresen: { ms: "Imigresen", en: "Immigration", zh: "移民管制", ta: "குடிவரவு", ko: "출입국 관리", th: 'การเข้าเมือง' },
  immigration: { ms: "Undang-Undang Imigresen", en: "Immigration law", zh: "移民法", ta: "குடிவரவுச் சட்டம்", ko: "출입국법", th: 'กฎหมายการเข้าเมือง' },
  incorporation: { ms: "Pemerbadanan", en: "Incorporation", zh: "公司注册成立", ta: "நிறுவன பதிவு", ko: "회사 설립", th: 'การจดทะเบียนจัดตั้งบริษัท' },
  inheritance: { ms: "Pewarisan Harta", en: "Property inheritance", zh: "房产继承", ta: "சொத்து வாரிசுரிமை", ko: "부동산 상속", th: 'การรับมรดกอสังหาริมทรัพย์' },
  insolvency: { ms: "Insolvensi", en: "Insolvency", zh: "破产清盘", ta: "திவால் நிலை", ko: "지급불능", th: 'ภาวะล้มละลาย' },
  investment: { ms: "Pelaburan", en: "Investment", zh: "投资", ta: "முதலீடு", ko: "투자", th: 'การลงทุน' },
  ip: { ms: "Harta Intelek", en: "Intellectual property", zh: "知识产权", ta: "அறிவுசார் சொத்து", ko: "지식재산권", th: 'ทรัพย์สินทางปัญญา' },
  judiciary: { ms: "Kehakiman", en: "Judiciary", zh: "司法机构", ta: "நீதித்துறை", ko: "사법부", th: 'ฝ่ายตุลาการ' },
  'kanak-kanak': { ms: "Pekerja Bawah Umur", en: "Child employment", zh: "童工", ta: "குழந்தை வேலைவாய்ப்பு", ko: "아동 노동", th: 'การจ้างแรงงานเด็ก' },
  kebankrapan: { ms: "Kebankrapan", en: "Bankruptcy", zh: "个人破产", ta: "திவால்", ko: "개인 파산", th: 'การล้มละลาย' },
  keris: { ms: "Keris", en: "The keris", zh: "马来短剑", ta: "கிரிஸ் கத்தி", ko: "크리스(단검)", th: 'กริช (keris)' },
  kesihatan: { ms: "Undang-Undang Kesihatan", en: "Health law", zh: "卫生法", ta: "சுகாதாரச் சட்டம்", ko: "보건법", th: 'กฎหมายสุขภาพ' },
  ketaksamaan: { ms: "Ketaksamaan Pendapatan", en: "Income inequality", zh: "收入不平等", ta: "வருமான ஏற்றத்தாழ்வு", ko: "소득 불평등", th: 'ความเหลื่อมล้ำทางรายได้' },
  keterangan: { ms: "Keterangan", en: "Evidence", zh: "证据法", ta: "சாட்சியம்", ko: "증거법", th: 'กฎหมายพยานหลักฐาน' },
  kewarganegaraan: { ms: "Kewarganegaraan", en: "Citizenship", zh: "公民权", ta: "குடியுரிமை", ko: "시민권", th: 'สัญชาติ' },
  komunikasi: { ms: "Komunikasi & Multimedia", en: "Communications & multimedia", zh: "通讯与多媒体", ta: "தகவல்தொடர்பு & பல்லூடகம்", ko: "통신 및 멀티미디어", th: 'การสื่อสารและมัลติมีเดีย' },
  kredit: { ms: "Kredit Pengguna", en: "Consumer credit", zh: "消费信贷", ta: "நுகர்வோர் கடன்", ko: "소비자 신용", th: 'สินเชื่อผู้บริโภค' },
  legalisasi: { ms: "Legalisasi Dokumen", en: "Document legalisation", zh: "文件认证", ta: "ஆவண சட்டப்பூர்வமாக்கல்", ko: "서류 인증", th: 'การรับรองเอกสาร' },
  levi: { ms: "Levi", en: "Levies", zh: "征费", ta: "லெவிகள்", ko: "부과금", th: 'ค่าธรรมเนียมพิเศษ' },
  liabiliti: { ms: "Liabiliti Statutori", en: "Statutory liability", zh: "法定责任", ta: "சட்டப்பூர்வ பொறுப்பு", ko: "법정 책임", th: 'ความรับผิดตามกฎหมาย' },
  litigasi: { ms: "Litigasi", en: "Litigation", zh: "诉讼", ta: "வழக்காடல்", ko: "소송", th: 'การดำเนินคดี' },
  llp: { ms: "PLT", en: "LLPs", zh: "有限责任合伙 (LLP)", ta: "LLP", ko: "LLP", th: 'ห้างหุ้นส่วนจำกัดความรับผิด (LLP)' },
  marriage: { ms: "Perkahwinan", en: "Marriage", zh: "婚姻登记", ta: "திருமணம்", ko: "혼인 등록", th: 'การจดทะเบียนสมรส' },
  materiality: { ms: "Materialiti", en: "Materiality", zh: "重要性", ta: "முக்கியத்துவம்", ko: "중요성", th: 'ความมีสาระสำคัญ' },
  mikromobiliti: { ms: "Mikromobiliti", en: "Micromobility", zh: "微型交通工具", ta: "நுண் போக்குவரத்து", ko: "마이크로모빌리티", th: 'ไมโครโมบิลิตี' },
  motosikal: { ms: "Motosikal", en: "Motorcycles", zh: "摩托车", ta: "மோட்டார் சைக்கிள்கள்", ko: "오토바이", th: 'รถจักรยานยนต์' },
  muet: { ms: "MUET & Kemasukan Universiti", en: "MUET & university entrance", zh: "MUET 与大学入学", ta: "MUET & பல்கலைக்கழக நுழைவு", ko: "MUET 및 대학 입학", th: 'MUET และการเข้าศึกษาต่อมหาวิทยาลัย' },
  nama: { ms: "Nama Syarikat", en: "Company name", zh: "公司名称", ta: "நிறுவனப் பெயர்", ko: "회사명", th: 'ชื่อบริษัท' },
  nasionalisme: { ms: "Nasionalisme", en: "Nationalism", zh: "民族主义", ta: "தேசியவாதம்", ko: "민족주의", th: 'ลัทธิชาตินิยม' },
  oku: { ms: "Pekerja OKU", en: "Employees with disabilities (OKU)", zh: "残障雇员 (OKU)", ta: "ஊனமுற்ற பணியாளர்கள் (OKU)", ko: "장애인 근로자(OKU)", th: 'ลูกจ้างผู้พิการ (OKU)' },
  overstay: { ms: "Tinggal Lebih Masa", en: "Overstaying", zh: "逾期居留", ta: "தங்கல் மீறல்", ko: "체류 기간 초과", th: 'การพำนักเกินกำหนด' },
  palmoil: { ms: "Levi Sawit", en: "Palm oil levy", zh: "棕油暴利税", ta: "பாமாயில் லெவி", ko: "팜유 부과금", th: 'ค่าธรรมเนียมน้ำมันปาล์ม' },
  parking: { ms: "Letak Kereta", en: "Parking", zh: "停车", ta: "வாகன நிறுத்தம்", ko: "주차", th: 'ที่จอดรถ' },
  'pekerja-asing': { ms: "Pekerja Asing", en: "Foreign workers", zh: "外籍劳工", ta: "வெளிநாட்டுத் தொழிலாளர்கள்", ko: "외국인 근로자", th: 'แรงงานต่างชาติ' },
  pekerjaan: { ms: "Undang-Undang Pekerjaan", en: "Employment law", zh: "就业法", ta: "வேலைவாய்ப்புச் சட்டம்", ko: "고용법", th: 'กฎหมายการจ้างงาน' },
  pelaporan: { ms: "Pelaporan Syarikat", en: "Corporate reporting", zh: "公司申报", ta: "நிறுவன அறிக்கையிடல்", ko: "기업 공시", th: 'การรายงานข้อมูลของบริษัท' },
  pembiayaan: { ms: "Pembiayaan Rumah", en: "Home financing", zh: "房贷", ta: "வீட்டு நிதியுதவி", ko: "주택 금융", th: 'สินเชื่อที่อยู่อาศัย' },
  pencatutan: { ms: "Pencatutan Harga", en: "Price profiteering", zh: "哄抬物价", ta: "விலை கொள்ளையடித்தல்", ko: "가격 폭리", th: 'การค้ากำไรเกินควร' },
  pendapatan: { ms: "Kumpulan Pendapatan", en: "Income groups", zh: "收入群体", ta: "வருமானக் குழுக்கள்", ko: "소득 계층", th: 'กลุ่มรายได้' },
  penerbitan: { ms: "Percetakan & Penerbitan", en: "Printing & publications", zh: "印刷与出版", ta: "அச்சிடுதல் & வெளியீடுகள்", ko: "인쇄 및 출판", th: 'การพิมพ์และสิ่งพิมพ์' },
  penyempurnaan: { ms: "Penyempurnaan Dokumen", en: "Executing documents", zh: "文件签立", ta: "ஆவணங்களை நிறைவேற்றல்", ko: "문서 작성·체결", th: 'การลงนามในเอกสาร' },
  peperiksaan: { ms: "Peperiksaan", en: "Examinations", zh: "考试", ta: "தேர்வுகள்", ko: "시험", th: 'การสอบ' },
  perjudian: { ms: "Duti Perjudian", en: "Gaming duties", zh: "博彩税", ta: "சூதாட்ட வரிகள்", ko: "도박세", th: 'ภาษีการพนัน' },
  perkahwinan: { ms: "Perkahwinan Sivil", en: "Civil marriage", zh: "民事婚姻", ta: "சிவில் திருமணம்", ko: "민사 혼인", th: 'การสมรสทางแพ่ง' },
  perlembagaan: { ms: "Perlembagaan Syarikat", en: "Company constitution", zh: "公司章程", ta: "நிறுவன அரசியலமைப்பு", ko: "회사 정관", th: 'ข้อบังคับบริษัท' },
  persaraan: { ms: "Persaraan", en: "Retirement", zh: "退休", ta: "ஓய்வு", ko: "은퇴", th: 'การเกษียณอายุ' },
  perumahan: { ms: "Pemajuan Perumahan", en: "Housing development", zh: "房屋发展", ta: "வீட்டுவசதி மேம்பாடு", ko: "주택 개발", th: 'การพัฒนาที่อยู่อาศัย' },
  pibg: { ms: "PIBG", en: "PTA (PIBG)", zh: "家教协会 (PIBG)", ta: "பெற்றோர்-ஆசிரியர் சங்கம் (PIBG)", ko: "학부모교사협회(PIBG)", th: 'สมาคมผู้ปกครองและครู (PIBG)' },
  pilihanraya: { ms: "Pilihan Raya", en: "Elections", zh: "选举", ta: "தேர்தல்கள்", ko: "선거", th: 'การเลือกตั้ง' },
  pintar: { ms: "Pendidikan Pintar", en: "Gifted education", zh: "资优教育", ta: "திறமைசாலிக் கல்வி", ko: "영재 교육", th: 'การศึกษาสำหรับผู้มีความสามารถพิเศษ' },
  plt: { ms: "PLT", en: "LLPs", zh: "有限责任合伙 (LLP)", ta: "LLP", ko: "LLP", th: 'ห้างหุ้นส่วนจำกัดความรับผิด (LLP)' },
  politics: { ms: "Politik", en: "Politics", zh: "政治", ta: "அரசியல்", ko: "정치", th: 'การเมือง' },
  procedure: { ms: "Tatacara Jenayah", en: "Criminal procedure", zh: "刑事程序", ta: "குற்றவியல் நடைமுறை", ko: "형사 절차", th: 'วิธีพิจารณาความอาญา' },
  profesion: { ms: "Profesion Guaman", en: "Legal profession", zh: "法律专业", ta: "சட்டத் தொழில்", ko: "법조 직역", th: 'วิชาชีพกฎหมาย' },
  prosecution: { ms: "Pendakwaan", en: "Prosecution", zh: "检控", ta: "வழக்குத் தொடுத்தல்", ko: "검찰 기소", th: 'การฟ้องร้องดำเนินคดี' },
  pusaka: { ms: "Pusaka Islam", en: "Islamic inheritance", zh: "伊斯兰遗产继承", ta: "இஸ்லாமிய வாரிசுரிமை", ko: "이슬람 상속", th: 'มรดกตามหลักอิสลาม' },
  puspakom: { ms: "Pemeriksaan Puspakom", en: "Puspakom inspections", zh: "Puspakom 车检", ta: "Puspakom ஆய்வுகள்", ko: "Puspakom 차량 검사", th: 'การตรวจสภาพรถ Puspakom' },
  rail: { ms: "Kereta Api", en: "Rail", zh: "铁路", ta: "ரயில்", ko: "철도", th: 'ระบบราง' },
  raja: { ms: "Institusi Diraja", en: "Monarchy", zh: "王室", ta: "முடியாட்சி", ko: "군주제", th: 'สถาบันพระมหากษัตริย์' },
  rankings: { ms: "Kedudukan Global", en: "Global rankings", zh: "全球排名", ta: "உலகளாவிய தரவரிசைகள்", ko: "세계 순위", th: 'อันดับระดับโลก' },
  ratings: { ms: "Penarafan Kredit", en: "Credit ratings", zh: "信用评级", ta: "கடன் மதிப்பீடுகள்", ko: "신용 등급", th: 'อันดับความน่าเชื่อถือทางเครดิต' },
  recruitment: { ms: "Pengambilan Pekerja", en: "Recruitment", zh: "招聘", ta: "ஆட்சேர்ப்பு", ko: "채용", th: 'การสรรหาบุคลากร' },
  redomiciliation: { ms: "Pemindahan Domisil", en: "Redomiciliation", zh: "迁册", ta: "குடியிருப்பு மாற்றம்", ko: "설립지 이전", th: 'การย้ายถิ่นที่จดทะเบียน' },
  reinstatement: { ms: "Pemulihan Syarikat", en: "Reinstatement", zh: "公司恢复", ta: "நிறுவன மீட்டமைப்பு", ko: "회사 회복", th: 'การคืนสถานะบริษัท' },
  reits: { ms: "REIT", en: "REITs", zh: "房地产投资信托 (REIT)", ta: "REIT", ko: "REIT", th: 'REIT' },
  'related-parties': { ms: "Pihak Berkaitan", en: "Related parties", zh: "关联方", ta: "தொடர்புடைய தரப்புகள்", ko: "특수관계자", th: 'บุคคลที่เกี่ยวข้องกัน' },
  renovation: { ms: "Ubah Suai Rumah", en: "Home renovation", zh: "房屋装修", ta: "வீடு புதுப்பித்தல்", ko: "주택 리모델링", th: 'การปรับปรุงต่อเติมบ้าน' },
  residency: { ms: "Pemastautin Tetap", en: "Permanent residency", zh: "永久居留", ta: "நிரந்தர வாசம்", ko: "영주권", th: 'การมีถิ่นที่อยู่ถาวร' },
  shareholders: { ms: "Pemegang Saham", en: "Shareholders", zh: "股东", ta: "பங்குதாரர்கள்", ko: "주주", th: 'ผู้ถือหุ้น' },
  siasatan: { ms: "Siasatan Cukai", en: "Tax investigation", zh: "税务调查", ta: "வரி விசாரணை", ko: "세무 조사", th: 'การตรวจสอบภาษี' },
  simbol: { ms: "Simbol Negara", en: "National symbols", zh: "国家象征", ta: "தேசிய சின்னங்கள்", ko: "국가 상징", th: 'สัญลักษณ์ของชาติ' },
  sovereignty: { ms: "Kedaulatan", en: "Sovereignty", zh: "主权", ta: "இறையாண்மை", ko: "주권", th: 'อธิปไตย' },
  'sports-governance': { ms: "Tadbir Urus Sukan", en: "Sports governance", zh: "体育管理", ta: "விளையாட்டு நிர்வாகம்", ko: "스포츠 거버넌스", th: 'การกำกับดูแลกีฬา' },
  strata: { ms: "Hakmilik Strata", en: "Strata living", zh: "分层产权", ta: "அடுக்கு உரிமை வாழ்க்கை", ko: "집합건물 생활", th: 'การอยู่อาศัยแบบอาคารชุด' },
  'strike-off': { ms: "Pemotongan Nama", en: "Striking off", zh: "公司除名", ta: "பெயர் நீக்கம்", ko: "회사 등록 말소", th: 'การถอนชื่อบริษัทออกจากทะเบียน' },
  syariah: { ms: "Syariah", en: "Syariah", zh: "伊斯兰教法", ta: "ஷரியா", ko: "샤리아", th: 'ชะรีอะฮ์' },
  takwim: { ms: "Takwim Persekolahan", en: "School calendar", zh: "校历", ta: "பள்ளி நாட்காட்டி", ko: "학사 일정", th: 'ปฏิทินการศึกษา' },
  talent: { ms: "Bakat", en: "Talent", zh: "人才", ta: "திறமை", ko: "인재", th: 'บุคลากรที่มีความสามารถ' },
  tenaga: { ms: "Tenaga", en: "Energy", zh: "能源", ta: "எரிசக்தி", ko: "에너지", th: 'พลังงาน' },
  tourism: { ms: "Cukai Pelancongan", en: "Tourism tax", zh: "旅游税", ta: "சுற்றுலா வரி", ko: "관광세", th: 'ภาษีการท่องเที่ยว' },
  tuisyen: { ms: "Tuisyen", en: "Tuition", zh: "补习", ta: "டியூஷன்", ko: "사교육", th: 'การเรียนกวดวิชา' },
  union: { ms: "Rundingan Kolektif", en: "Collective bargaining", zh: "集体谈判", ta: "கூட்டு பேரம்", ko: "단체 교섭", th: 'การเจรจาต่อรองร่วม' },
  unions: { ms: "Kesatuan Sekerja", en: "Trade unions", zh: "工会", ta: "தொழிற்சங்கங்கள்", ko: "노동조합", th: 'สหภาพแรงงาน' },
  universities: { ms: "Universiti", en: "Universities", zh: "大学", ta: "பல்கலைக்கழகங்கள்", ko: "대학", th: 'มหาวิทยาลัย' },
  visas: { ms: "Visa", en: "Visas", zh: "签证", ta: "விசாக்கள்", ko: "비자", th: 'วีซ่า' },
  wawasan: { ms: "Wawasan Negara", en: "National vision", zh: "国家愿景", ta: "தேசிய தொலைநோக்கு", ko: "국가 비전", th: 'วิสัยทัศน์แห่งชาติ' },
  whistleblowing: { ms: "Perlindungan Pemberi Maklumat", en: "Whistleblower protection", zh: "举报人保护", ta: "தகவல் அறிவிப்பாளர் பாதுகாப்பு", ko: "내부고발자 보호", th: 'การคุ้มครองผู้แจ้งเบาะแส' },
};

/** Display order per category. Anything unlisted sorts to the end. */
export const SUBCATEGORY_ORDER: Record<string, string[]> = {
  // Ordered as a reader's journey, not alphabetically: decide → register →
  // get licensed → fund it → protect it → grow it → exit.
  business: [
    'formation',
    'choosing-a-structure',
    'structuring',
    'registration',
    'licensing',
    'foreign-ownership',
    'ownership',
    'banking-finance',
    'banking',
    'contracts-disputes',
    'intellectual-property',
    'digital-compliance',
    'economic-corridors',
    'locations',
    'closing',
  ],
  'company-secretary': [
    'appointment',
    'statutory-registers',
    'filings',
    'directors',
    'meetings-resolutions',
    'share-capital',
    'beneficial-ownership',
    'governance',
  ],
  taxation: [
    'corporate-tax',
    'personal-tax',
    'deductions-and-allowances',
    'sst',
    'e-invoicing',
    'withholding-tax',
    'international-tax',
    'capital-taxes',
    'stamp-duty',
    'incentives',
    'tax-administration',
  ],
  accounting: ['standards', 'records', 'financial-statements', 'bookkeeping', 'financial-year'],
  audit: ['requirements', 'audit-appointment', 'appointment', 'fees', 'process', 'reporting'],
  employment: [
    'employment-law-basics',
    'hiring-and-contracts',
    'hiring',
    'payroll-statutory',
    'leave-and-welfare',
    'termination-retrenchment',
    'foreign-workers-expatriates',
    'labour-law',
  ],
  states: ['peninsular', 'borneo', 'territories', 'state-government'],
  // ---- living ----
  transport: ['public-transport', 'driving', 'vehicles-tolls'],
  'money-daily-life': ['banking-payments', 'personal-tax-statutory', 'everyday-admin'],
  'settling-in': ['visas-passes', 'documents'],
  'cost-of-living': ['overview', 'by-city'],
  property: ['renting', 'buying', 'home-ownership', 'utilities', 'community'],
  healthcare: ['overview', 'using-the-system', 'insurance', 'specialised'],
  education: ['overview', 'schooling', 'exams', 'tertiary', 'financing', 'support', 'skills'],
  malaysia: [
    'early-kingdoms',
    'sultanates',
    'colonial',
    'occupation',
    'independence',
    'nation-formation',
    'modern',
    'identity',
  ],
  'arts-culture': ['performing-arts', 'crafts', 'festivals', 'languages', 'heritage'],
  law: ['constitutional', 'legal-system', 'key-acts', 'corporate', 'tax', 'employment'],
  government: ['institutions', 'agencies', 'ministries'],
  economy: ['indicators', 'monetary-policy', 'sectors', 'policy', 'institutions', 'trade'],
  // Civic terms first — the glossary's job is explaining the state to a reader.
  glossary: ['government', 'legal', 'corporate', 'tax', 'employment', 'culture'],
};

function titleCase(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

export function subcatLabel(slug: string, locale: Locale): string {
  return SUBCATEGORY_LABELS[slug]?.[locale as ContentLocale] ?? titleCase(slug);
}

/** Ordered subcategory slugs present in a set of articles. */
export function orderedSubcats(categoryId: string, present: string[]): string[] {
  const order = SUBCATEGORY_ORDER[categoryId] ?? [];
  const seen = [...new Set(present)];
  return seen.sort((a, b) => {
    const ia = order.indexOf(a);
    const ib = order.indexOf(b);
    return (ia === -1 ? 999 : ia) - (ib === -1 ? 999 : ib);
  });
}
