import type { ContentLocale, Locale, Localized } from './categories';

// Sub-topic clusters. Labels are written the way a READER would say them,
// not in internal taxonomy language. Target 5–15 articles per cluster.
// SUBCATEGORY_ORDER controls display order within a category page.

export const SUBCATEGORY_LABELS: Record<string, Localized> = {
  // ---- business ----
  formation: { ms: 'Asas Penubuhan', en: 'Formation fundamentals', zh: '公司设立基础', ta: 'நிறுவன அமைப்பு அடிப்படைகள்' },
  'choosing-a-structure': { ms: 'Memilih Struktur', en: 'Choosing a structure', zh: '选择商业结构', ta: 'கட்டமைப்பைத் தேர்ந்தெடுத்தல்' },
  registration: { ms: 'Prosedur Pendaftaran', en: 'Registration procedures', zh: '注册程序', ta: 'பதிவு நடைமுறைகள்' },
  licensing: { ms: 'Lesen & Permit', en: 'Licences & permits', zh: '执照与准证', ta: 'உரிமங்கள் & அனுமதிகள்' },
  'foreign-ownership': { ms: 'Pemilikan & Pelabur Asing', en: 'Foreign founders & ownership', zh: '外资与股权', ta: 'வெளிநாட்டு நிறுவனர்கள் & உரிமை' },
  'banking-finance': { ms: 'Perbankan, Kewangan & Kawalan Pertukaran', en: 'Banking, finance & exchange control', zh: '银行、融资与外汇管制', ta: 'வங்கி, நிதி & நாணய மாற்றுக் கட்டுப்பாடு' },
  'contracts-disputes': { ms: 'Kontrak & Pertikaian', en: 'Contracts & disputes', zh: '合约与纠纷', ta: 'ஒப்பந்தங்கள் & தகராறுகள்' },
  'intellectual-property': { ms: 'Harta Intelek', en: 'Intellectual property', zh: '知识产权', ta: 'அறிவுசார் சொத்து' },
  'economic-corridors': { ms: 'Koridor Ekonomi', en: 'Where to invest — regions & corridors', zh: '经济走廊与投资地点', ta: 'எங்கு முதலீடு செய்வது — பகுதிகள் & வழித்தடங்கள்' },
  locations: { ms: 'Berniaga Mengikut Lokasi', en: 'Doing business by location', zh: '各地经商指南', ta: 'இடம் வாரியாக வணிகம்' },
  'digital-compliance': { ms: 'Pematuhan Digital', en: 'Digital compliance', zh: '数字合规', ta: 'டிஜிட்டல் இணக்கம்' },
  closing: { ms: 'Penstrukturan & Penutupan', en: 'Restructuring & closure', zh: '重组与结业', ta: 'மறுசீரமைப்பு & மூடல்' },
  // legacy keys, kept so older articles still label correctly
  ownership: { ms: 'Pemilikan & Pelabur Asing', en: 'Foreign founders & ownership', zh: '外资与股权', ta: 'வெளிநாட்டு நிறுவனர்கள் & உரிமை' },
  structuring: { ms: 'Struktur & Entiti', en: 'Structuring & entities', zh: '架构与实体', ta: 'கட்டமைப்பு & நிறுவனங்கள்' },
  banking: { ms: 'Perbankan & Kewangan', en: 'Banking & finance setup', zh: '银行与融资', ta: 'வங்கி & நிதி அமைப்பு' },

  // ---- company secretary ----
  appointment: { ms: 'Pelantikan & Kelayakan', en: 'Appointment & qualification', zh: '委任与资格', ta: 'நியமனம் & தகுதி' },
  'statutory-registers': { ms: 'Daftar Berkanun & Rekod', en: 'Statutory registers & records', zh: '法定登记册与记录', ta: 'சட்டப்பூர்வ பதிவேடுகள் & பதிவுகள்' },
  filings: { ms: 'Penyata Tahunan & Pemfailan', en: 'Annual return & filings', zh: '年报与申报', ta: 'ஆண்டறிக்கை & தாக்கல்கள்' },
  directors: { ms: 'Tugas & Pendedahan Pengarah', en: "Directors' duties & disclosures", zh: '董事职责与披露', ta: 'இயக்குநர்களின் கடமைகள் & வெளிப்பாடுகள்' },
  'meetings-resolutions': { ms: 'Mesyuarat & Resolusi', en: 'Meetings & resolutions', zh: '会议与决议', ta: 'கூட்டங்கள் & தீர்மானங்கள்' },
  'share-capital': { ms: 'Modal Saham & Pemindahan', en: 'Share capital & transfers', zh: '股本与股份转让', ta: 'பங்கு மூலதனம் & பரிமாற்றங்கள்' },
  'beneficial-ownership': { ms: 'Pemilik Benefisial', en: 'Beneficial ownership', zh: '实益拥有权', ta: 'பயனாளி உரிமை' },
  governance: { ms: 'Tadbir Urus', en: 'Governance', zh: '公司治理', ta: 'ஆளுகை' },

  // ---- taxation ----
  'corporate-tax': { ms: 'Cukai Korporat', en: 'Corporate tax', zh: '企业税', ta: 'நிறுவன வரி' },
  'personal-tax': { ms: 'Cukai Individu', en: 'Personal tax', zh: '个人税', ta: 'தனிநபர் வரி' },
  'deductions-and-allowances': { ms: 'Potongan & Elaun', en: 'Deductions & allowances', zh: '扣除与津贴', ta: 'கழிவுகள் & கொடுப்பனவுகள்' },
  sst: { ms: 'SST', en: 'Sales & Service Tax', zh: '销售与服务税', ta: 'விற்பனை & சேவை வரி (SST)' },
  'e-invoicing': { ms: 'e-Invois', en: 'E-invoicing', zh: '电子发票', ta: 'மின் விலைப்பட்டியல்' },
  'withholding-tax': { ms: 'Cukai Pegangan', en: 'Withholding tax', zh: '预扣税', ta: 'நிறுத்திவைப்பு வரி' },
  'international-tax': { ms: 'Cukai Antarabangsa', en: 'International tax', zh: '国际税务', ta: 'சர்வதேச வரி' },
  'capital-taxes': { ms: 'Cukai Keuntungan Modal', en: 'Taxes on capital', zh: '资本利得税', ta: 'மூலதன வரிகள்' },
  'stamp-duty': { ms: 'Duti Setem', en: 'Stamp duty', zh: '印花税', ta: 'முத்திரை வரி' },
  incentives: { ms: 'Insentif Cukai', en: 'Tax incentives', zh: '税务优惠', ta: 'வரி ஊக்கத்தொகைகள்' },
  'tax-administration': { ms: 'Pentadbiran Cukai', en: 'Tax administration', zh: '税务行政', ta: 'வரி நிர்வாகம்' },

  // ---- accounting ----
  standards: { ms: 'Piawaian Perakaunan', en: 'Accounting standards', zh: '会计准则', ta: 'கணக்கியல் தரநிலைகள்' },
  records: { ms: 'Rekod Perakaunan', en: 'Accounting records', zh: '会计记录', ta: 'கணக்கியல் பதிவுகள்' },
  'financial-statements': { ms: 'Penyata Kewangan & MBRS', en: 'Financial statements & MBRS', zh: '财务报表与 MBRS', ta: 'நிதி அறிக்கைகள் & MBRS' },
  bookkeeping: { ms: 'Simpan Kira', en: 'Bookkeeping', zh: '簿记', ta: 'கணக்குப் பதிவு' },
  'financial-year': { ms: 'Tahun Kewangan', en: 'Financial year end', zh: '财政年结', ta: 'நிதியாண்டு முடிவு' },

  // ---- audit ----
  requirements: { ms: 'Keperluan & Pengecualian', en: 'Requirements & exemption', zh: '审计要求与豁免', ta: 'தேவைகள் & விலக்கு' },
  'audit-appointment': { ms: 'Melantik Juruaudit', en: 'Appointing an auditor', zh: '委任审计师', ta: 'தணிக்கையாளர் நியமனம்' },
  fees: { ms: 'Yuran Audit', en: 'Audit fees', zh: '审计费用', ta: 'தணிக்கைக் கட்டணங்கள்' },
  process: { ms: 'Proses Audit', en: 'The audit process', zh: '审计流程', ta: 'தணிக்கை நடைமுறை' },
  reporting: { ms: 'Jenis Laporan', en: 'Report types', zh: '报告类型', ta: 'அறிக்கை வகைகள்' },

  // ---- employment ----
  'employment-law-basics': { ms: 'Asas Undang-Undang Pekerjaan', en: 'Employment law basics', zh: '劳动法基础', ta: 'வேலைவாய்ப்புச் சட்ட அடிப்படைகள்' },
  'hiring-and-contracts': { ms: 'Pengambilan & Kontrak', en: 'Hiring & contracts', zh: '招聘与合约', ta: 'பணியமர்த்தல் & ஒப்பந்தங்கள்' },
  'payroll-statutory': { ms: 'Gaji & Caruman Berkanun', en: 'Payroll & statutory', zh: '薪资与法定缴纳', ta: 'ஊதியம் & சட்டப்பூர்வக் கட்டணங்கள்' },
  'leave-and-welfare': { ms: 'Cuti & Kebajikan', en: 'Leave, benefits & welfare', zh: '假期与福利', ta: 'விடுப்பு, சலுகைகள் & நலன்' },
  'termination-retrenchment': { ms: 'Penamatan & Pemberhentian', en: 'Termination & retrenchment', zh: '解雇与裁员', ta: 'பணிநீக்கம் & பணிக்குறைப்பு' },
  'foreign-workers-expatriates': { ms: 'Pekerja Asing & Ekspatriat', en: 'Foreign workers & expatriates', zh: '外籍员工与外派人员', ta: 'வெளிநாட்டுத் தொழிலாளர்கள் & வெளிநாட்டவர்கள்' },
  hiring: { ms: 'Pengambilan Pekerja', en: 'Hiring', zh: '招聘', ta: 'பணியமர்த்தல்' },
  'labour-law': { ms: 'Undang-Undang Buruh', en: 'Labour law', zh: '劳工法', ta: 'தொழிலாளர் சட்டம்' },

  // ---- states ----
  peninsular: { ms: 'Semenanjung', en: 'Peninsular Malaysia', zh: '马来半岛', ta: 'தீபகற்ப மலேசியா' },
  borneo: { ms: 'Borneo', en: 'Borneo', zh: '婆罗洲', ta: 'போர்னியோ' },
  territories: { ms: 'Wilayah Persekutuan', en: 'Federal Territories', zh: '联邦直辖区', ta: 'கூட்டாட்சிப் பிரதேசங்கள்' },
  'state-government': { ms: 'Kerajaan Negeri', en: 'State government', zh: '州政府', ta: 'மாநில அரசாங்கம்' },

  // ---- living: transport ----
  'public-transport': { ms: 'Pengangkutan Awam', en: 'Public transport', zh: '公共交通', ta: 'பொதுப் போக்குவரத்து' },
  driving: { ms: 'Memandu', en: 'Driving', zh: '驾驶', ta: 'வாகனம் ஓட்டுதல்' },
  'vehicles-tolls': { ms: 'Kenderaan & Tol', en: 'Vehicles & tolls', zh: '车辆与过路费', ta: 'வாகனங்கள் & சுங்கச்சாவடி' },
  // ---- living: money & daily life ----
  'banking-payments': { ms: 'Perbankan & Pembayaran', en: 'Banking & payments', zh: '银行与支付', ta: 'வங்கி & கட்டணங்கள்' },
  'personal-tax-statutory': { ms: 'Cukai & Caruman', en: 'Tax & statutory', zh: '税务与法定缴纳', ta: 'வரி & சட்டப்பூர்வக் கட்டணங்கள்' },
  'everyday-admin': { ms: 'Urusan Harian', en: 'Everyday admin', zh: '日常事务', ta: 'அன்றாட நிர்வாகப் பணிகள்' },
  // ---- living: settling in ----
  'visas-passes': { ms: 'Visa & Pas', en: 'Visas & passes', zh: '签证与准证', ta: 'விசாக்கள் & அனுமதிச்சீட்டுகள்' },
  documents: { ms: 'Dokumen', en: 'Documents', zh: '证件', ta: 'ஆவணங்கள்' },
  // ---- living: cost of living / housing / healthcare ----
  overview: { ms: 'Gambaran', en: 'Overview', zh: '概览', ta: 'மேலோட்டம்' },
  'by-city': { ms: 'Mengikut Bandar', en: 'By city', zh: '按城市', ta: 'நகரம் வாரியாக' },
  renting: { ms: 'Menyewa', en: 'Renting', zh: '租房', ta: 'வாடகை' },
  buying: { ms: 'Membeli Rumah', en: 'Buying', zh: '购房', ta: 'வீடு வாங்குதல்' },
  'home-ownership': { ms: 'Pemilikan & Cukai', en: 'Ownership & tax', zh: '产权与税', ta: 'உரிமை & வரி' },
  community: { ms: 'Kejiranan', en: 'Community living', zh: '社区生活', ta: 'சமூக வாழ்க்கை' },
  utilities: { ms: 'Utiliti', en: 'Utilities', zh: '水电网络', ta: 'பயன்பாட்டு சேவைகள்' },
  'using-the-system': { ms: 'Menggunakan Sistem', en: 'Using the system', zh: '使用系统', ta: 'அமைப்பைப் பயன்படுத்துதல்' },
  insurance: { ms: 'Insurans Perubatan', en: 'Medical insurance', zh: '医疗保险', ta: 'மருத்துவக் காப்பீடு' },
  specialised: { ms: 'Penjagaan Khusus', en: 'Specialised care', zh: '专项护理', ta: 'சிறப்புப் பராமரிப்பு' },
  schooling: { ms: 'Persekolahan', en: 'Schooling', zh: '就学', ta: 'பள்ளிக் கல்வி' },
  exams: { ms: 'Peperiksaan', en: 'Exams', zh: '考试', ta: 'தேர்வுகள்' },
  tertiary: { ms: 'Pengajian Tinggi', en: 'Higher education', zh: '高等教育', ta: 'உயர்கல்வி' },
  financing: { ms: 'Pembiayaan', en: 'Financing', zh: '教育资助', ta: 'நிதியுதவி' },
  support: { ms: 'Sokongan Pembelajaran', en: 'Learning support', zh: '学习支持', ta: 'கற்றல் ஆதரவு' },
  skills: { ms: 'Latihan Kemahiran', en: 'Skills training', zh: '技能培训', ta: 'திறன் பயிற்சி' },

  // ---- malaysia (history & identity) ----
  'early-kingdoms': { ms: 'Kerajaan Awal', en: 'Early kingdoms', zh: '早期王国', ta: 'ஆரம்பகால இராச்சியங்கள்' },
  sultanates: { ms: 'Kesultanan Melayu', en: 'Malay sultanates', zh: '马来苏丹王朝', ta: 'மலாய் சுல்தானகங்கள்' },
  colonial: { ms: 'Zaman Penjajahan', en: 'Colonial era', zh: '殖民时代', ta: 'காலனித்துவ காலம்' },
  occupation: { ms: 'Pendudukan Jepun', en: 'Japanese occupation', zh: '日据时期', ta: 'ஜப்பானியர் ஆக்கிரமிப்பு' },
  independence: { ms: 'Ke Arah Kemerdekaan', en: 'Towards independence', zh: '迈向独立', ta: 'சுதந்திரத்தை நோக்கி' },
  'nation-formation': { ms: 'Pembentukan Malaysia', en: 'Forming Malaysia', zh: '马来西亚的成立', ta: 'மலேசியாவின் உருவாக்கம்' },
  modern: { ms: 'Malaysia Moden', en: 'Modern Malaysia', zh: '现代马来西亚', ta: 'நவீன மலேசியா' },
  identity: { ms: 'Identiti Nasional', en: 'National identity', zh: '国家认同', ta: 'தேசிய அடையாளம்' },

  // ---- arts & culture ----
  'performing-arts': { ms: 'Seni Persembahan', en: 'Performing arts', zh: '表演艺术', ta: 'நிகழ்த்துக் கலைகள்' },
  crafts: { ms: 'Kraf Tangan', en: 'Crafts', zh: '手工艺', ta: 'கைவினைப் பொருட்கள்' },
  festivals: { ms: 'Perayaan', en: 'Festivals', zh: '节庆', ta: 'பண்டிகைகள்' },
  languages: { ms: 'Bahasa', en: 'Languages', zh: '语言', ta: 'மொழிகள்' },
  heritage: { ms: 'Warisan', en: 'Heritage', zh: '文化遗产', ta: 'பாரம்பரியம்' },

  // ---- law ----
  corporate: { ms: 'Korporat', en: 'Corporate', zh: '公司法', ta: 'நிறுவனம்' },
  tax: { ms: 'Percukaian', en: 'Taxation', zh: '税务', ta: 'வரிவிதிப்பு' },
  employment: { ms: 'Pekerjaan', en: 'Employment', zh: '就业', ta: 'வேலைவாய்ப்பு' },
  'legal-system': { ms: 'Sistem Perundangan', en: 'Legal system', zh: '法律体系', ta: 'சட்ட அமைப்பு' },
  'key-acts': { ms: 'Akta Utama', en: 'Key Acts', zh: '主要法令', ta: 'முக்கிய சட்டங்கள்' },
  // ---- glossary (civic terms) ----
  government: { ms: 'Kerajaan', en: 'Government', zh: '政府', ta: 'அரசாங்கம்' },
  legal: { ms: 'Perundangan', en: 'Legal', zh: '法律', ta: 'சட்டம்' },
  culture: { ms: 'Budaya', en: 'Culture', zh: '文化', ta: 'கலாச்சாரம்' },
  constitutional: { ms: 'Perlembagaan', en: 'Constitutional', zh: '宪法', ta: 'அரசியலமைப்பு' },

  // ---- government ----
  agencies: { ms: 'Agensi', en: 'Agencies', zh: '机构', ta: 'முகமைகள்' },
  institutions: { ms: 'Institusi', en: 'Institutions', zh: '体制机构', ta: 'நிறுவனங்கள்' },
  ministries: { ms: 'Kementerian', en: 'Ministries', zh: '部门', ta: 'அமைச்சுகள்' },

  // ---- economy ----
  indicators: { ms: 'Petunjuk', en: 'Indicators', zh: '指标', ta: 'குறியீடுகள்' },
  sectors: { ms: 'Sektor', en: 'Sectors', zh: '行业领域', ta: 'துறைகள்' },
  trade: { ms: 'Perdagangan', en: 'Trade', zh: '贸易', ta: 'வர்த்தகம்' },
  'monetary-policy': { ms: 'Dasar Monetari', en: 'Monetary policy', zh: '货币政策', ta: 'நாணயக் கொள்கை' },
  policy: { ms: 'Dasar', en: 'Policy', zh: '政策', ta: 'கொள்கை' },
  // `institutions` is already defined under government above — shared label.

  // ---- Phase 2: topic labels for newly-populated categories ----
  // agriculture
  beras: { ms: "Perdagangan Beras", en: "Rice trade", zh: "大米贸易", ta: "அரிசி வர்த்தகம்" },
  felda: { ms: "FELDA", en: "FELDA", zh: "联邦土地发展局 (FELDA)", ta: "FELDA" },
  'food-security': { ms: "Keterjaminan Makanan", en: "Food security", zh: "粮食安全", ta: "உணவுப் பாதுகாப்பு" },
  livestock: { ms: "Ternakan", en: "Livestock", zh: "畜牧业", ta: "கால்நடை வளர்ப்பு" },
  padi: { ms: "Padi", en: "Rice (padi)", zh: "稻米种植", ta: "நெல் (பாடி)" },
  'pekebun-kecil': { ms: "Pekebun Kecil", en: "Smallholders", zh: "小园主", ta: "சிறுதோட்டக்காரர்கள்" },
  pemasaran: { ms: "Pemasaran Pertanian", en: "Agricultural marketing", zh: "农产品营销", ta: "வேளாண் சந்தைப்படுத்தல்" },
  perikanan: { ms: "Perikanan", en: "Fisheries", zh: "渔业", ta: "மீன்வளம்" },
  research: { ms: "Penyelidikan Pertanian", en: "Agricultural research", zh: "农业研究", ta: "வேளாண் ஆராய்ச்சி" },
  smallholders: { ms: "Pekebun Kecil", en: "Smallholders", zh: "小园主", ta: "சிறுதோட்டக்காரர்கள்" },
  // agriculture/companies
  plantation: { ms: "Perladangan", en: "Plantations", zh: "种植园", ta: "தோட்டங்கள்" },
  // agriculture/food-lifestyle
  durian: { ms: "Durian & Buah Tropika", en: "Durian & tropical fruit", zh: "榴莲与热带水果", ta: "துரியான் & வெப்பமண்டல பழங்கள்" },
  // arts-culture
  attire: { ms: "Pakaian Tradisional", en: "Traditional attire", zh: "传统服饰", ta: "பாரம்பரிய உடை" },
  film: { ms: "Filem", en: "Film", zh: "电影", ta: "திரைப்படம்" },
  kebudayaan: { ms: "Dasar Kebudayaan", en: "Cultural policy", zh: "文化政策", ta: "கலாச்சாரக் கொள்கை" },
  language: { ms: "Bahasa", en: "Language", zh: "语言", ta: "மொழி" },
  'martial-arts': { ms: "Silat & Seni Bela Diri", en: "Martial arts", zh: "武术", ta: "தற்காப்புக் கலைகள்" },
  music: { ms: "Muzik", en: "Music", zh: "音乐", ta: "இசை" },
  sastera: { ms: "Sastera", en: "Literature", zh: "文学", ta: "இலக்கியம்" },
  senibina: { ms: "Seni Bina", en: "Architecture", zh: "建筑", ta: "கட்டிடக்கலை" },
  tarian: { ms: "Tarian Tradisional", en: "Traditional dance", zh: "传统舞蹈", ta: "பாரம்பரிய நடனம்" },
  warisan: { ms: "Warisan", en: "Heritage", zh: "文化遗产", ta: "பாரம்பரியம்" },
  // companies
  conglomerates: { ms: "Konglomerat", en: "Conglomerates", zh: "企业集团", ta: "கூட்டு நிறுவனங்கள்" },
  glc: { ms: "GLC & GLIC", en: "GLCs & GLICs", zh: "官联公司 (GLC)", ta: "GLC & GLIC" },
  kewangan: { ms: "Kumpulan Kewangan", en: "Financial groups", zh: "金融集团", ta: "நிதிக் குழுமங்கள்" },
  lebuhraya: { ms: "Lebuh Raya", en: "Highways", zh: "高速公路", ta: "நெடுஞ்சாலைகள்" },
  pelaburan: { ms: "Dana Pelaburan", en: "Investment funds", zh: "投资基金", ta: "முதலீட்டு நிதிகள்" },
  pencen: { ms: "Dana Persaraan", en: "Retirement funds", zh: "退休基金", ta: "ஓய்வூதிய நிதிகள்" },
  pension: { ms: "Dana Pencen", en: "Pension funds", zh: "退休基金", ta: "ஓய்வூதிய நிதிகள்" },
  // companies/energy
  petroleum: { ms: "Petroleum", en: "Petroleum", zh: "石油", ta: "பெட்ரோலியம்" },
  utiliti: { ms: "Utiliti", en: "Utilities", zh: "公用事业", ta: "பயன்பாட்டு சேவைகள்" },
  // companies/glossary
  'sovereign-wealth': { ms: "Dana Kekayaan Negara", en: "Sovereign wealth", zh: "主权财富基金", ta: "இறையாண்மைச் செல்வம்" },
  // companies/industries
  manufacturing: { ms: "Pembuatan", en: "Manufacturing", zh: "制造业", ta: "உற்பத்தித் துறை" },
  // companies/technology
  telecoms: { ms: "Telekomunikasi", en: "Telecoms", zh: "电信", ta: "தொலைத்தொடர்பு" },
  // energy
  elektrik: { ms: "Bekalan Elektrik", en: "Electricity supply", zh: "电力供应", ta: "மின்சார விநியோகம்" },
  fuel: { ms: "Harga Bahan Api", en: "Fuel pricing", zh: "燃油定价", ta: "எரிபொருள் விலை" },
  gas: { ms: "Gas Asli & LNG", en: "Natural gas & LNG", zh: "天然气与液化天然气", ta: "இயற்கை எரிவாயு & LNG" },
  hydrogen: { ms: "Hidrogen & CCUS", en: "Hydrogen & CCUS", zh: "氢能与碳捕集", ta: "ஹைட்ரஜன் & CCUS" },
  hydropower: { ms: "Hidrokuasa", en: "Hydropower", zh: "水力发电", ta: "நீர்மின்சக்தி" },
  perundangan: { ms: "Perundangan Tenaga", en: "Energy legislation", zh: "能源立法", ta: "எரிசக்திச் சட்டம்" },
  reform: { ms: "Reformasi Tenaga", en: "Energy reform", zh: "能源改革", ta: "எரிசக்தி சீர்திருத்தம்" },
  renewables: { ms: "Tenaga Boleh Baharu", en: "Renewables", zh: "可再生能源", ta: "புதுப்பிக்கத்தக்க எரிசக்தி" },
  solar: { ms: "Tenaga Solar", en: "Solar power", zh: "太阳能", ta: "சூரிய சக்தி" },
  subsidi: { ms: "Subsidi Bahan Api", en: "Fuel subsidies", zh: "燃油补贴", ta: "எரிபொருள் மானியங்கள்" },
  tarif: { ms: "Tarif Elektrik", en: "Electricity tariffs", zh: "电费费率", ta: "மின்சாரக் கட்டணங்கள்" },
  // energy/finance/glossary/technology
  regulator: { ms: "Pengawal Selia", en: "Regulators", zh: "监管机构", ta: "ஒழுங்குமுறை ஆணையங்கள்" },
  // environment
  'EIA': { ms: "Penilaian Impak Alam (EIA)", en: "Environmental impact (EIA)", zh: "环境影响评估 (EIA)", ta: "சுற்றுச்சூழல் தாக்க மதிப்பீடு (EIA)" },
  carbon: { ms: "Pasaran Karbon", en: "Carbon market", zh: "碳市场", ta: "கார்பன் சந்தை" },
  climate: { ms: "Dasar Iklim", en: "Climate policy", zh: "气候政策", ta: "காலநிலைக் கொள்கை" },
  forests: { ms: "Penebangan Hutan", en: "Deforestation", zh: "森林砍伐", ta: "காடழிப்பு" },
  jerebu: { ms: "Jerebu", en: "Haze", zh: "烟霾", ta: "புகைமூட்டம்" },
  land: { ms: "Tanah & Hak Adat", en: "Land & customary rights", zh: "土地与习俗权利", ta: "நிலம் & வழக்கமான உரிமைகள்" },
  pemuliharaan: { ms: "Pemuliharaan", en: "Conservation", zh: "自然保护", ta: "இயற்கைப் பாதுகாப்பு" },
  penyu: { ms: "Penyu & Pemuliharaan Marin", en: "Turtles & marine conservation", zh: "海龟与海洋保护", ta: "ஆமைகள் & கடல் பாதுகாப்பு" },
  perhutanan: { ms: "Hutan Simpan", en: "Forest reserves", zh: "森林保护区", ta: "காப்புக் காடுகள்" },
  plastik: { ms: "Pencemaran Plastik", en: "Plastic pollution", zh: "塑料污染", ta: "பிளாஸ்டிக் மாசு" },
  pollution: { ms: "Undang-Undang Alam Sekitar", en: "Environmental law", zh: "环境法", ta: "சுற்றுச்சூழல் சட்டம்" },
  udara: { ms: "Kualiti Udara", en: "Air quality", zh: "空气质量", ta: "காற்றின் தரம்" },
  waste: { ms: "Pengurusan Sisa", en: "Waste management", zh: "废物管理", ta: "கழிவு மேலாண்மை" },
  water: { ms: "Keselamatan Air", en: "Water security", zh: "水资源安全", ta: "நீர்ப் பாதுகாப்பு" },
  wildlife: { ms: "Hidupan Liar", en: "Wildlife", zh: "野生动物", ta: "வனவிலங்குகள்" },
  // environment/industries
  'palm-oil': { ms: "Minyak Sawit", en: "Palm oil", zh: "棕榈油", ta: "பாமாயில்" },
  // finance
  bonds: { ms: "Pasaran Bon", en: "Bond market", zh: "债券市场", ta: "பத்திரச் சந்தை" },
  'capital-markets': { ms: "Pasaran Modal", en: "Capital markets", zh: "资本市场", ta: "மூலதனச் சந்தைகள்" },
  credit: { ms: "Laporan Kredit", en: "Credit reporting", zh: "信用报告", ta: "கடன் அறிக்கையிடல்" },
  fintech: { ms: "Fintech", en: "Fintech", zh: "金融科技", ta: "ஃபின்டெக்" },
  investing: { ms: "Pelaburan", en: "Investing", zh: "投资", ta: "முதலீடு" },
  lending: { ms: "Pembiayaan & Pinjaman", en: "Lending & financing", zh: "贷款与融资", ta: "கடன் & நிதியுதவி" },
  payments: { ms: "Sistem Pembayaran", en: "Payments", zh: "支付系统", ta: "கட்டணங்கள்" },
  retirement: { ms: "Simpanan Persaraan", en: "Retirement savings", zh: "退休储蓄", ta: "ஓய்வுக்காலச் சேமிப்பு" },
  takaful: { ms: "Takaful & Insurans", en: "Takaful & insurance", zh: "伊斯兰保险与保险", ta: "தகாஃபுல் & காப்பீடு" },
  // food-lifestyle
  alcohol: { ms: "Peraturan Alkohol", en: "Alcohol rules", zh: "酒类法规", ta: "மது விதிகள்" },
  cuisine: { ms: "Juadah Perayaan", en: "Festive cuisine", zh: "节庆美食", ta: "பண்டிகை உணவு" },
  dining: { ms: "Pilihan Pemakanan", en: "Dietary dining", zh: "饮食选择", ta: "உணவுமுறை சார்ந்த உணவகம்" },
  hiburan: { ms: "Hiburan", en: "Entertainment", zh: "娱乐", ta: "பொழுதுபோக்கு" },
  kopitiam: { ms: "Budaya Kopitiam", en: "Kopitiam culture", zh: "咖啡店文化", ta: "கோபிதியாம் கலாச்சாரம்" },
  makanan: { ms: "Hidangan Kebangsaan", en: "National dishes", zh: "国民美食", ta: "தேசிய உணவுகள்" },
  masakan: { ms: "Masakan Serantau", en: "Regional cuisine", zh: "地方菜系", ta: "பிராந்திய உணவுகள்" },
  pasar: { ms: "Pasar Rakyat", en: "Markets & street food", zh: "市集与街头美食", ta: "சந்தைகள் & தெரு உணவு" },
  ramadan: { ms: "Bazar Ramadan", en: "Ramadan bazaars", zh: "斋月市集", ta: "ரமலான் பஜார்கள்" },
  retail: { ms: "Runcit & Beli-belah", en: "Retail & shopping", zh: "零售与购物", ta: "சில்லறை & ஷாப்பிங்" },
  // food-lifestyle/glossary/industries
  halal: { ms: "Halal", en: "Halal", zh: "清真认证", ta: "ஹலால்" },
  // glossary
  kenegaraan: { ms: "Kenegaraan", en: "Nationhood", zh: "国家理念", ta: "தேசியம்" },
  kerajaan: { ms: "Kerajaan", en: "Government", zh: "政府", ta: "அரசாங்கம்" },
  peribumi: { ms: "Orang Asli", en: "Indigenous Peoples", zh: "原住民", ta: "பழங்குடி மக்கள்" },
  tanah: { ms: "Tanah", en: "Land", zh: "土地", ta: "நிலம்" },
  zakat: { ms: "Zakat", en: "Zakat", zh: "天课 (Zakat)", ta: "ஜகாத் (Zakat)" },
  // glossary/government
  monarki: { ms: "Institusi Diraja", en: "Monarchy", zh: "王室", ta: "முடியாட்சி" },
  // glossary/industries
  economy: { ms: "Ekonomi", en: "Economy", zh: "经济", ta: "பொருளாதாரம்" },
  // glossary/public-safety
  polis: { ms: "Polis", en: "Police", zh: "警察", ta: "காவல்துறை" },
  // government
  autonomi: { ms: "Autonomi Sabah & Sarawak", en: "Sabah & Sarawak autonomy", zh: "沙巴与砂拉越自治", ta: "சபா & சரவாக் சுயாட்சி" },
  'central-bank': { ms: "Bank Pusat", en: "Central bank", zh: "中央银行", ta: "மத்திய வங்கி" },
  citizenship: { ms: "Kewarganegaraan", en: "Citizenship", zh: "公民权", ta: "குடியுரிமை" },
  constitution: { ms: "Perlembagaan", en: "Constitution", zh: "宪法", ta: "அரசியலமைப்பு" },
  kehakiman: { ms: "Kehakiman", en: "Judiciary", zh: "司法", ta: "நீதித்துறை" },
  parties: { ms: "Parti Politik", en: "Political parties", zh: "政党", ta: "அரசியல் கட்சிகள்" },
  pertahanan: { ms: "Pertahanan", en: "Defence", zh: "国防", ta: "பாதுகாப்பு" },
  transparency: { ms: "Ketelusan", en: "Transparency", zh: "政府透明度", ta: "வெளிப்படைத்தன்மை" },
  treasury: { ms: "Perbendaharaan", en: "Treasury", zh: "财政部", ta: "கருவூலம்" },
  // government/international
  diplomacy: { ms: "Diplomasi", en: "Diplomacy", zh: "外交", ta: "இராஜதந்திரம்" },
  // government/public-safety
  keselamatan: { ms: "Keselamatan Negara", en: "National security", zh: "国家安全", ta: "தேசியப் பாதுகாப்பு" },
  // healthcare
  darah: { ms: "Pendermaan Darah", en: "Blood donation", zh: "献血", ta: "இரத்த தானம்" },
  'digital-health': { ms: "Kesihatan Digital", en: "Digital health", zh: "数字医疗", ta: "டிஜிட்டல் சுகாதாரம்" },
  disability: { ms: "OKU & Kesihatan", en: "Disability & health", zh: "残障与健康", ta: "ஊனம் & சுகாதாரம்" },
  hiv: { ms: "HIV & Kesihatan Seksual", en: "HIV & sexual health", zh: "艾滋病与性健康", ta: "HIV & பாலியல் சுகாதாரம்" },
  ncd: { ms: "Penyakit Tidak Berjangkit", en: "Noncommunicable diseases", zh: "非传染性疾病", ta: "தொற்றா நோய்கள்" },
  paliatif: { ms: "Penjagaan Paliatif", en: "Palliative care", zh: "缓和医疗", ta: "நோய்த்தணிப்பு பராமரிப்பு" },
  pandemik: { ms: "Pandemik", en: "Pandemics", zh: "疫情", ta: "கொள்ளைநோய்கள்" },
  pendaftaran: { ms: "Pendaftaran Profesional", en: "Professional registration", zh: "专业注册", ta: "தொழில்முறை பதிவு" },
  pengguguran: { ms: "Pengguguran", en: "Abortion", zh: "堕胎", ta: "கருக்கலைப்பு" },
  reformasi: { ms: "Reformasi Kesihatan", en: "Health reform", zh: "医疗改革", ta: "சுகாதார சீர்திருத்தம்" },
  telemedicine: { ms: "Teleperubatan", en: "Telemedicine", zh: "远程医疗", ta: "தொலைமருத்துவம்" },
  tembakau: { ms: "Kawalan Tembakau", en: "Tobacco control", zh: "烟草管制", ta: "புகையிலைக் கட்டுப்பாடு" },
  transplan: { ms: "Pendermaan Organ", en: "Organ donation", zh: "器官捐赠", ta: "உறுப்பு தானம்" },
  vaksin: { ms: "Vaksin", en: "Vaccines", zh: "疫苗", ta: "தடுப்பூசிகள்" },
  // industries
  aerospace: { ms: "Aeroangkasa & MRO", en: "Aerospace & MRO", zh: "航空航天与维修", ta: "வான்வெளி & MRO" },
  automotive: { ms: "Automotif", en: "Automotive", zh: "汽车业", ta: "வாகனத் துறை" },
  bumiputera: { ms: "Ekuiti Bumiputera", en: "Bumiputera equity", zh: "土著股权", ta: "பூமிபுத்ரா பங்கு" },
  construction: { ms: "Pembinaan", en: "Construction", zh: "建筑业", ta: "கட்டுமானத் துறை" },
  energy: { ms: "Minyak & Gas", en: "Oil & gas", zh: "石油与天然气", ta: "எண்ணெய் & எரிவாயு" },
  logistics: { ms: "Logistik & Pelabuhan", en: "Logistics & ports", zh: "物流与港口", ta: "தளவாடம் & துறைமுகங்கள்" },
  rubber: { ms: "Industri Getah", en: "Rubber industry", zh: "橡胶业", ta: "ரப்பர் தொழில்" },
  semiconductors: { ms: "Semikonduktor", en: "Semiconductors", zh: "半导体", ta: "அரைக்கடத்திகள்" },
  // industries/technology
  datacentres: { ms: "Pusat Data", en: "Data centres", zh: "数据中心", ta: "தரவு மையங்கள்" },
  digital: { ms: "Ekonomi Digital", en: "Digital economy", zh: "数字经济", ta: "டிஜிட்டல் பொருளாதாரம்" },
  // international
  asean: { ms: "ASEAN", en: "ASEAN", zh: "东盟 (ASEAN)", ta: "ASEAN" },
  bilateral: { ms: "Hubungan Dwihala", en: "Bilateral relations", zh: "双边关系", ta: "இருதரப்பு உறவுகள்" },
  diplomasi: { ms: "Hubungan Serantau", en: "Regional relations", zh: "区域关系", ta: "பிராந்திய உறவுகள்" },
  singapore: { ms: "Singapura", en: "Singapore", zh: "新加坡", ta: "சிங்கப்பூர்" },
  // international/public-safety
  maritim: { ms: "Pertikaian Maritim", en: "Maritime disputes", zh: "海事争端", ta: "கடல்சார் தகராறுகள்" },
  // malaysia
  'country-basics': { ms: "Asas Negara", en: "Country basics", zh: "国家概况", ta: "நாட்டு அடிப்படைகள்" },
  demographics: { ms: "Demografi", en: "Demographics", zh: "人口结构", ta: "மக்கள்தொகையியல்" },
  geography: { ms: "Geografi", en: "Geography", zh: "地理", ta: "புவியியல்" },
  // public-safety
  banjir: { ms: "Banjir", en: "Floods", zh: "水灾", ta: "வெள்ளம்" },
  bencana: { ms: "Pengurusan Bencana", en: "Disaster management", zh: "灾害管理", ta: "பேரிடர் மேலாண்மை" },
  kebakaran: { ms: "Keselamatan Kebakaran", en: "Fire safety", zh: "消防安全", ta: "தீ பாதுகாப்பு" },
  kecemasan: { ms: "Perkhidmatan Kecemasan", en: "Emergency services", zh: "紧急服务", ta: "அவசர சேவைகள்" },
  komuniti: { ms: "Keselamatan Komuniti", en: "Community safety", zh: "社区安全", ta: "சமூகப் பாதுகாப்பு" },
  penipuan: { ms: "Penipuan & Jenayah Kewangan", en: "Scams & financial crime", zh: "诈骗与金融犯罪", ta: "மோசடிகள் & நிதிக் குற்றம்" },
  'pertahanan-diri': { ms: "Pertahanan Diri", en: "Self-defence", zh: "自卫", ta: "தற்காப்பு" },
  policing: { ms: "Kepolisan", en: "Policing", zh: "警务", ta: "காவல் பணி" },
  rela: { ms: "RELA", en: "RELA", zh: "人民志愿警卫队 (RELA)", ta: "RELA" },
  traffic: { ms: "Keselamatan Jalan Raya", en: "Road safety", zh: "道路安全", ta: "சாலைப் பாதுகாப்பு" },
  // sports
  badminton: { ms: "Badminton", en: "Badminton", zh: "羽毛球", ta: "பூப்பந்து" },
  bolasepak: { ms: "Liga Bola Sepak", en: "Football leagues", zh: "足球联赛", ta: "கால்பந்து லீக்குகள்" },
  cycling: { ms: "Lumba Basikal", en: "Cycling", zh: "自行车运动", ta: "மிதிவண்டி பந்தயம்" },
  football: { ms: "Bola Sepak", en: "Football", zh: "足球", ta: "கால்பந்து" },
  hoki: { ms: "Hoki", en: "Hockey", zh: "曲棍球", ta: "ஹாக்கி" },
  integriti: { ms: "Integriti Sukan", en: "Sports integrity", zh: "体育诚信", ta: "விளையாட்டு நேர்மை" },
  medals: { ms: "Rekod Pingat", en: "Medal record", zh: "奖牌纪录", ta: "பதக்கச் சாதனை" },
  motorsport: { ms: "Sukan Motor", en: "Motorsport", zh: "赛车运动", ta: "மோட்டார் விளையாட்டு" },
  naturalisasi: { ms: "Naturalisasi Sukan", en: "Sports naturalisation", zh: "体育归化", ta: "விளையாட்டு குடியுரிமை வழங்கல்" },
  paralimpik: { ms: "Paralimpik", en: "Paralympics", zh: "残奥会", ta: "பாராலிம்பிக்" },
  participation: { ms: "Penyertaan Sukan", en: "Sports participation", zh: "体育参与", ta: "விளையாட்டுப் பங்கேற்பு" },
  squash: { ms: "Skuasy", en: "Squash", zh: "壁球", ta: "ஸ்குவாஷ்" },
  sukma: { ms: "SUKMA", en: "SUKMA", zh: "马来西亚运动会 (SUKMA)", ta: "SUKMA" },
  takraw: { ms: "Sepak Takraw", en: "Sepak takraw", zh: "藤球", ta: "செபாக் தக்ரா" },
  venue: { ms: "Gelanggang Sukan", en: "Sports venues", zh: "体育场馆", ta: "விளையாட்டு அரங்குகள்" },
  // technology
  cybersecurity: { ms: "Keselamatan Siber", en: "Cybersecurity", zh: "网络安全", ta: "இணையப் பாதுகாப்பு" },
  dasar: { ms: "Dasar Digital", en: "Digital policy", zh: "数字政策", ta: "டிஜிட்டல் கொள்கை" },
  'digital-identity': { ms: "Identiti Digital", en: "Digital identity", zh: "数字身份", ta: "டிஜிட்டல் அடையாளம்" },
  kementerian: { ms: "Kementerian Digital", en: "Digital ministry", zh: "数字部", ta: "டிஜிட்டல் அமைச்சு" },
  startups: { ms: "Ekosistem Startup", en: "Startups", zh: "创业生态", ta: "தொடக்க நிறுவனங்கள்" },
  // tourism
  destinations: { ms: "Destinasi", en: "Destinations", zh: "旅游目的地", ta: "சுற்றுலா தலங்கள்" },
  diving: { ms: "Menyelam & Ekopelancongan Marin", en: "Diving & marine ecotourism", zh: "潜水与海洋生态旅游", ta: "நீர்மூழ்கல் & கடல் சுற்றுச்சூழல் சுற்றுலா" },
  events: { ms: "MICE & Acara", en: "MICE & events", zh: "会展旅游", ta: "MICE & நிகழ்வுகள்" },
  healthcare: { ms: "Pelancongan Perubatan", en: "Medical tourism", zh: "医疗旅游", ta: "மருத்துவ சுற்றுலா" },
  highlands: { ms: "Tanah Tinggi", en: "Highlands", zh: "高原地区", ta: "மலைப்பகுதிகள்" },
  islands: { ms: "Pulau", en: "Islands", zh: "海岛", ta: "தீவுகள்" },
  kualalumpur: { ms: "Kuala Lumpur", en: "Kuala Lumpur", zh: "吉隆坡", ta: "கோலாலம்பூர்" },
  langkawi: { ms: "Langkawi", en: "Langkawi", zh: "兰卡威", ta: "லங்காவி" },
  planning: { ms: "Tip Perancangan", en: "Trip planning", zh: "行程规划", ta: "பயணத் திட்டமிடல்" },
  rainforest: { ms: "Hutan Hujan", en: "Rainforest", zh: "雨林", ta: "மழைக்காடு" },
  sabah: { ms: "Sabah", en: "Sabah", zh: "沙巴", ta: "சபா" },
  sarawak: { ms: "Sarawak", en: "Sarawak", zh: "砂拉越", ta: "சரவாக்" },
  transport: { ms: "Pengangkutan", en: "Getting around", zh: "交通出行", ta: "போக்குவரத்து" },
  visa: { ms: "Syarat Kemasukan", en: "Entry requirements", zh: "入境要求", ta: "நுழைவுத் தேவைகள்" },
  // ---- auto-filled: subcategory keys used by articles but previously unlabelled
  //      (fell back to the raw slug on every locale). Trilingual labels added.
  accreditation: { ms: "Akreditasi", en: "Accreditation", zh: "学历认证", ta: "அங்கீகாரம்" },
  agama: { ms: "Pendidikan Agama", en: "Religious education", zh: "宗教教育", ta: "மத கல்வி" },
  amalgamation: { ms: "Penggabungan Syarikat", en: "Amalgamation", zh: "公司合并", ta: "நிறுவன இணைப்பு" },
  'anti-corruption': { ms: "Antirasuah", en: "Anti-corruption", zh: "反贪腐", ta: "ஊழல் எதிர்ப்பு" },
  arbitration: { ms: "Timbang Tara", en: "Arbitration", zh: "仲裁", ta: "நடுவர் தீர்ப்பு" },
  assurance: { ms: "Jaminan Audit", en: "Assurance", zh: "鉴证", ta: "உறுதிப்படுத்தல்" },
  auction: { ms: "Lelongan", en: "Auctions", zh: "拍卖", ta: "ஏலம்" },
  audit: { ms: "Audit", en: "Audit", zh: "审计", ta: "தணிக்கை" },
  auditor: { ms: "Juruaudit", en: "Auditors", zh: "审计师", ta: "தணிக்கையாளர்கள்" },
  'bantuan-guaman': { ms: "Bantuan Guaman", en: "Legal aid", zh: "法律援助", ta: "சட்ட உதவி" },
  belanjawan: { ms: "Belanjawan Isi Rumah", en: "Household budgeting", zh: "家庭预算", ta: "குடும்ப பட்ஜெட்" },
  biasiswa: { ms: "Biasiswa", en: "Scholarships", zh: "奖学金", ta: "புலமைப்பரிசில்கள்" },
  boarding: { ms: "Sekolah Berasrama", en: "Boarding schools", zh: "寄宿学校", ta: "தங்கும் விடுதிப் பள்ளிகள்" },
  buruh: { ms: "Undang-Undang Buruh", en: "Labour law", zh: "劳工法", ta: "தொழிலாளர் சட்டம்" },
  buses: { ms: "Perkhidmatan Bas", en: "Buses", zh: "巴士", ta: "பேருந்துகள்" },
  competition: { ms: "Persaingan", en: "Competition", zh: "竞争法", ta: "போட்டி" },
  compliance: { ms: "Pematuhan", en: "Compliance", zh: "合规", ta: "இணக்கம்" },
  consolidation: { ms: "Penyata Disatukan", en: "Consolidation", zh: "合并报表", ta: "ஒருங்கிணைந்த கணக்குகள்" },
  conversion: { ms: "Penukaran Status", en: "Conversion", zh: "公司转型", ta: "நிலை மாற்றம்" },
  cukai: { ms: "Percukaian", en: "Taxation", zh: "税务", ta: "வரிவிதிப்பு" },
  currency: { ms: "Mata Wang", en: "Currency", zh: "货币", ta: "நாணயம்" },
  customs: { ms: "Duti Kastam", en: "Customs duty", zh: "关税", ta: "சுங்க வரி" },
  daerah: { ms: "Pentadbiran Daerah", en: "District administration", zh: "县级行政", ta: "மாவட்ட நிர்வாகம்" },
  'digital-assets': { ms: "Aset Digital", en: "Digital assets", zh: "数字资产", ta: "டிஜிட்டல் சொத்துகள்" },
  disclosure: { ms: "Pendedahan", en: "Disclosures", zh: "披露", ta: "வெளிப்பாடுகள்" },
  divorce: { ms: "Perceraian", en: "Divorce", zh: "离婚", ta: "விவாகரத்து" },
  egumis: { ms: "Wang Tak Dituntut", en: "Unclaimed money", zh: "无人认领款项", ta: "உரிமை கோராத பணம்" },
  ejen: { ms: "Ejen Hartanah", en: "Property agents", zh: "房地产中介", ta: "சொத்து முகவர்கள்" },
  environment: { ms: "Alam Sekitar", en: "Environmental law", zh: "环境法", ta: "சுற்றுச்சூழல் சட்டம்" },
  estate: { ms: "Cukai Warisan", en: "Estate & inheritance tax", zh: "遗产税", ta: "சொத்து & வாரிசு வரி" },
  ev: { ms: "Kenderaan Elektrik", en: "Electric vehicles", zh: "电动车", ta: "மின்சார வாகனங்கள்" },
  ewallet: { ms: "E-Dompet", en: "E-wallets", zh: "电子钱包", ta: "மின் பணப்பைகள்" },
  excise: { ms: "Duti Eksais", en: "Excise duty", zh: "国产税", ta: "கலால் வரி" },
  ferries: { ms: "Feri", en: "Ferries", zh: "渡轮", ta: "படகுகள்" },
  'financial-regulation': { ms: "Pengawalan Kewangan", en: "Financial regulation", zh: "金融监管", ta: "நிதி ஒழுங்குமுறை" },
  'fisheries-governance': { ms: "Tadbir Urus Perikanan", en: "Fisheries governance", zh: "渔业管理", ta: "மீன்வள மேலாண்மை" },
  fiskal: { ms: "Kewangan Negeri", en: "State finances", zh: "州财政", ta: "மாநில நிதி" },
  foreign: { ms: "Syarikat Asing", en: "Foreign companies", zh: "外国公司", ta: "வெளிநாட்டு நிறுவனங்கள்" },
  franchise: { ms: "Francais", en: "Franchising", zh: "特许经营", ta: "உரிமையாக்கம்" },
  gaji: { ms: "Gaji & Potongan", en: "Wages", zh: "薪资", ta: "ஊதியம்" },
  gig: { ms: "Pekerja Gig", en: "Gig workers", zh: "零工工作者", ta: "கிக் தொழிலாளர்கள்" },
  'hak-asasi': { ms: "Hak Asasi Manusia", en: "Human rights", zh: "人权", ta: "மனித உரிமைகள்" },
  history: { ms: "Sejarah", en: "History", zh: "历史", ta: "வரலாறு" },
  homebuyer: { ms: "Perlindungan Pembeli Rumah", en: "Homebuyer protection", zh: "购房者保护", ta: "வீடு வாங்குவோர் பாதுகாப்பு" },
  hutang: { ms: "Hutang", en: "Debt", zh: "债务", ta: "கடன்" },
  imigresen: { ms: "Imigresen", en: "Immigration", zh: "移民管制", ta: "குடிவரவு" },
  immigration: { ms: "Undang-Undang Imigresen", en: "Immigration law", zh: "移民法", ta: "குடிவரவுச் சட்டம்" },
  incorporation: { ms: "Pemerbadanan", en: "Incorporation", zh: "公司注册成立", ta: "நிறுவன பதிவு" },
  inheritance: { ms: "Pewarisan Harta", en: "Property inheritance", zh: "房产继承", ta: "சொத்து வாரிசுரிமை" },
  insolvency: { ms: "Insolvensi", en: "Insolvency", zh: "破产清盘", ta: "திவால் நிலை" },
  investment: { ms: "Pelaburan", en: "Investment", zh: "投资", ta: "முதலீடு" },
  ip: { ms: "Harta Intelek", en: "Intellectual property", zh: "知识产权", ta: "அறிவுசார் சொத்து" },
  judiciary: { ms: "Kehakiman", en: "Judiciary", zh: "司法机构", ta: "நீதித்துறை" },
  'kanak-kanak': { ms: "Pekerja Bawah Umur", en: "Child employment", zh: "童工", ta: "குழந்தை வேலைவாய்ப்பு" },
  kebankrapan: { ms: "Kebankrapan", en: "Bankruptcy", zh: "个人破产", ta: "திவால்" },
  keris: { ms: "Keris", en: "The keris", zh: "马来短剑", ta: "கிரிஸ் கத்தி" },
  kesihatan: { ms: "Undang-Undang Kesihatan", en: "Health law", zh: "卫生法", ta: "சுகாதாரச் சட்டம்" },
  ketaksamaan: { ms: "Ketaksamaan Pendapatan", en: "Income inequality", zh: "收入不平等", ta: "வருமான ஏற்றத்தாழ்வு" },
  keterangan: { ms: "Keterangan", en: "Evidence", zh: "证据法", ta: "சாட்சியம்" },
  kewarganegaraan: { ms: "Kewarganegaraan", en: "Citizenship", zh: "公民权", ta: "குடியுரிமை" },
  komunikasi: { ms: "Komunikasi & Multimedia", en: "Communications & multimedia", zh: "通讯与多媒体", ta: "தகவல்தொடர்பு & பல்லூடகம்" },
  kredit: { ms: "Kredit Pengguna", en: "Consumer credit", zh: "消费信贷", ta: "நுகர்வோர் கடன்" },
  legalisasi: { ms: "Legalisasi Dokumen", en: "Document legalisation", zh: "文件认证", ta: "ஆவண சட்டப்பூர்வமாக்கல்" },
  levi: { ms: "Levi", en: "Levies", zh: "征费", ta: "லெவிகள்" },
  liabiliti: { ms: "Liabiliti Statutori", en: "Statutory liability", zh: "法定责任", ta: "சட்டப்பூர்வ பொறுப்பு" },
  litigasi: { ms: "Litigasi", en: "Litigation", zh: "诉讼", ta: "வழக்காடல்" },
  llp: { ms: "PLT", en: "LLPs", zh: "有限责任合伙 (LLP)", ta: "LLP" },
  marriage: { ms: "Perkahwinan", en: "Marriage", zh: "婚姻登记", ta: "திருமணம்" },
  materiality: { ms: "Materialiti", en: "Materiality", zh: "重要性", ta: "முக்கியத்துவம்" },
  mikromobiliti: { ms: "Mikromobiliti", en: "Micromobility", zh: "微型交通工具", ta: "நுண் போக்குவரத்து" },
  motosikal: { ms: "Motosikal", en: "Motorcycles", zh: "摩托车", ta: "மோட்டார் சைக்கிள்கள்" },
  muet: { ms: "MUET & Kemasukan Universiti", en: "MUET & university entrance", zh: "MUET 与大学入学", ta: "MUET & பல்கலைக்கழக நுழைவு" },
  nama: { ms: "Nama Syarikat", en: "Company name", zh: "公司名称", ta: "நிறுவனப் பெயர்" },
  nasionalisme: { ms: "Nasionalisme", en: "Nationalism", zh: "民族主义", ta: "தேசியவாதம்" },
  oku: { ms: "Pekerja OKU", en: "Employees with disabilities (OKU)", zh: "残障雇员 (OKU)", ta: "ஊனமுற்ற பணியாளர்கள் (OKU)" },
  overstay: { ms: "Tinggal Lebih Masa", en: "Overstaying", zh: "逾期居留", ta: "தங்கல் மீறல்" },
  palmoil: { ms: "Levi Sawit", en: "Palm oil levy", zh: "棕油暴利税", ta: "பாமாயில் லெவி" },
  parking: { ms: "Letak Kereta", en: "Parking", zh: "停车", ta: "வாகன நிறுத்தம்" },
  'pekerja-asing': { ms: "Pekerja Asing", en: "Foreign workers", zh: "外籍劳工", ta: "வெளிநாட்டுத் தொழிலாளர்கள்" },
  pekerjaan: { ms: "Undang-Undang Pekerjaan", en: "Employment law", zh: "就业法", ta: "வேலைவாய்ப்புச் சட்டம்" },
  pelaporan: { ms: "Pelaporan Syarikat", en: "Corporate reporting", zh: "公司申报", ta: "நிறுவன அறிக்கையிடல்" },
  pembiayaan: { ms: "Pembiayaan Rumah", en: "Home financing", zh: "房贷", ta: "வீட்டு நிதியுதவி" },
  pencatutan: { ms: "Pencatutan Harga", en: "Price profiteering", zh: "哄抬物价", ta: "விலை கொள்ளையடித்தல்" },
  pendapatan: { ms: "Kumpulan Pendapatan", en: "Income groups", zh: "收入群体", ta: "வருமானக் குழுக்கள்" },
  penerbitan: { ms: "Percetakan & Penerbitan", en: "Printing & publications", zh: "印刷与出版", ta: "அச்சிடுதல் & வெளியீடுகள்" },
  penyempurnaan: { ms: "Penyempurnaan Dokumen", en: "Executing documents", zh: "文件签立", ta: "ஆவணங்களை நிறைவேற்றல்" },
  peperiksaan: { ms: "Peperiksaan", en: "Examinations", zh: "考试", ta: "தேர்வுகள்" },
  perjudian: { ms: "Duti Perjudian", en: "Gaming duties", zh: "博彩税", ta: "சூதாட்ட வரிகள்" },
  perkahwinan: { ms: "Perkahwinan Sivil", en: "Civil marriage", zh: "民事婚姻", ta: "சிவில் திருமணம்" },
  perlembagaan: { ms: "Perlembagaan Syarikat", en: "Company constitution", zh: "公司章程", ta: "நிறுவன அரசியலமைப்பு" },
  persaraan: { ms: "Persaraan", en: "Retirement", zh: "退休", ta: "ஓய்வு" },
  perumahan: { ms: "Pemajuan Perumahan", en: "Housing development", zh: "房屋发展", ta: "வீட்டுவசதி மேம்பாடு" },
  pibg: { ms: "PIBG", en: "PTA (PIBG)", zh: "家教协会 (PIBG)", ta: "பெற்றோர்-ஆசிரியர் சங்கம் (PIBG)" },
  pilihanraya: { ms: "Pilihan Raya", en: "Elections", zh: "选举", ta: "தேர்தல்கள்" },
  pintar: { ms: "Pendidikan Pintar", en: "Gifted education", zh: "资优教育", ta: "திறமைசாலிக் கல்வி" },
  plt: { ms: "PLT", en: "LLPs", zh: "有限责任合伙 (LLP)", ta: "LLP" },
  politics: { ms: "Politik", en: "Politics", zh: "政治", ta: "அரசியல்" },
  procedure: { ms: "Tatacara Jenayah", en: "Criminal procedure", zh: "刑事程序", ta: "குற்றவியல் நடைமுறை" },
  profesion: { ms: "Profesion Guaman", en: "Legal profession", zh: "法律专业", ta: "சட்டத் தொழில்" },
  prosecution: { ms: "Pendakwaan", en: "Prosecution", zh: "检控", ta: "வழக்குத் தொடுத்தல்" },
  pusaka: { ms: "Pusaka Islam", en: "Islamic inheritance", zh: "伊斯兰遗产继承", ta: "இஸ்லாமிய வாரிசுரிமை" },
  puspakom: { ms: "Pemeriksaan Puspakom", en: "Puspakom inspections", zh: "Puspakom 车检", ta: "Puspakom ஆய்வுகள்" },
  rail: { ms: "Kereta Api", en: "Rail", zh: "铁路", ta: "ரயில்" },
  raja: { ms: "Institusi Diraja", en: "Monarchy", zh: "王室", ta: "முடியாட்சி" },
  rankings: { ms: "Kedudukan Global", en: "Global rankings", zh: "全球排名", ta: "உலகளாவிய தரவரிசைகள்" },
  ratings: { ms: "Penarafan Kredit", en: "Credit ratings", zh: "信用评级", ta: "கடன் மதிப்பீடுகள்" },
  recruitment: { ms: "Pengambilan Pekerja", en: "Recruitment", zh: "招聘", ta: "ஆட்சேர்ப்பு" },
  redomiciliation: { ms: "Pemindahan Domisil", en: "Redomiciliation", zh: "迁册", ta: "குடியிருப்பு மாற்றம்" },
  reinstatement: { ms: "Pemulihan Syarikat", en: "Reinstatement", zh: "公司恢复", ta: "நிறுவன மீட்டமைப்பு" },
  reits: { ms: "REIT", en: "REITs", zh: "房地产投资信托 (REIT)", ta: "REIT" },
  'related-parties': { ms: "Pihak Berkaitan", en: "Related parties", zh: "关联方", ta: "தொடர்புடைய தரப்புகள்" },
  renovation: { ms: "Ubah Suai Rumah", en: "Home renovation", zh: "房屋装修", ta: "வீடு புதுப்பித்தல்" },
  residency: { ms: "Pemastautin Tetap", en: "Permanent residency", zh: "永久居留", ta: "நிரந்தர வாசம்" },
  shareholders: { ms: "Pemegang Saham", en: "Shareholders", zh: "股东", ta: "பங்குதாரர்கள்" },
  siasatan: { ms: "Siasatan Cukai", en: "Tax investigation", zh: "税务调查", ta: "வரி விசாரணை" },
  simbol: { ms: "Simbol Negara", en: "National symbols", zh: "国家象征", ta: "தேசிய சின்னங்கள்" },
  sovereignty: { ms: "Kedaulatan", en: "Sovereignty", zh: "主权", ta: "இறையாண்மை" },
  'sports-governance': { ms: "Tadbir Urus Sukan", en: "Sports governance", zh: "体育管理", ta: "விளையாட்டு நிர்வாகம்" },
  strata: { ms: "Hakmilik Strata", en: "Strata living", zh: "分层产权", ta: "அடுக்கு உரிமை வாழ்க்கை" },
  'strike-off': { ms: "Pemotongan Nama", en: "Striking off", zh: "公司除名", ta: "பெயர் நீக்கம்" },
  syariah: { ms: "Syariah", en: "Syariah", zh: "伊斯兰教法", ta: "ஷரியா" },
  takwim: { ms: "Takwim Persekolahan", en: "School calendar", zh: "校历", ta: "பள்ளி நாட்காட்டி" },
  talent: { ms: "Bakat", en: "Talent", zh: "人才", ta: "திறமை" },
  tenaga: { ms: "Tenaga", en: "Energy", zh: "能源", ta: "எரிசக்தி" },
  tourism: { ms: "Cukai Pelancongan", en: "Tourism tax", zh: "旅游税", ta: "சுற்றுலா வரி" },
  tuisyen: { ms: "Tuisyen", en: "Tuition", zh: "补习", ta: "டியூஷன்" },
  union: { ms: "Rundingan Kolektif", en: "Collective bargaining", zh: "集体谈判", ta: "கூட்டு பேரம்" },
  unions: { ms: "Kesatuan Sekerja", en: "Trade unions", zh: "工会", ta: "தொழிற்சங்கங்கள்" },
  universities: { ms: "Universiti", en: "Universities", zh: "大学", ta: "பல்கலைக்கழகங்கள்" },
  visas: { ms: "Visa", en: "Visas", zh: "签证", ta: "விசாக்கள்" },
  wawasan: { ms: "Wawasan Negara", en: "National vision", zh: "国家愿景", ta: "தேசிய தொலைநோக்கு" },
  whistleblowing: { ms: "Perlindungan Pemberi Maklumat", en: "Whistleblower protection", zh: "举报人保护", ta: "தகவல் அறிவிப்பாளர் பாதுகாப்பு" },
};

/** Display order per category. Anything unlisted sorts to the end. */
export const SUBCATEGORY_ORDER: Record<string, string[]> = {
  // Ordered as a reader's journey, not alphabetically: decide → register →
  // get licensed → fund it → protect it → grow it → exit.
  business: [
    'formation',
    'choosing-a-structure',
    'structuring',
    'registration',
    'licensing',
    'foreign-ownership',
    'ownership',
    'banking-finance',
    'banking',
    'contracts-disputes',
    'intellectual-property',
    'digital-compliance',
    'economic-corridors',
    'locations',
    'closing',
  ],
  'company-secretary': [
    'appointment',
    'statutory-registers',
    'filings',
    'directors',
    'meetings-resolutions',
    'share-capital',
    'beneficial-ownership',
    'governance',
  ],
  taxation: [
    'corporate-tax',
    'personal-tax',
    'deductions-and-allowances',
    'sst',
    'e-invoicing',
    'withholding-tax',
    'international-tax',
    'capital-taxes',
    'stamp-duty',
    'incentives',
    'tax-administration',
  ],
  accounting: ['standards', 'records', 'financial-statements', 'bookkeeping', 'financial-year'],
  audit: ['requirements', 'audit-appointment', 'appointment', 'fees', 'process', 'reporting'],
  employment: [
    'employment-law-basics',
    'hiring-and-contracts',
    'hiring',
    'payroll-statutory',
    'leave-and-welfare',
    'termination-retrenchment',
    'foreign-workers-expatriates',
    'labour-law',
  ],
  states: ['peninsular', 'borneo', 'territories', 'state-government'],
  // ---- living ----
  transport: ['public-transport', 'driving', 'vehicles-tolls'],
  'money-daily-life': ['banking-payments', 'personal-tax-statutory', 'everyday-admin'],
  'settling-in': ['visas-passes', 'documents'],
  'cost-of-living': ['overview', 'by-city'],
  property: ['renting', 'buying', 'home-ownership', 'utilities', 'community'],
  healthcare: ['overview', 'using-the-system', 'insurance', 'specialised'],
  education: ['overview', 'schooling', 'exams', 'tertiary', 'financing', 'support', 'skills'],
  malaysia: [
    'early-kingdoms',
    'sultanates',
    'colonial',
    'occupation',
    'independence',
    'nation-formation',
    'modern',
    'identity',
  ],
  'arts-culture': ['performing-arts', 'crafts', 'festivals', 'languages', 'heritage'],
  law: ['constitutional', 'legal-system', 'key-acts', 'corporate', 'tax', 'employment'],
  government: ['institutions', 'agencies', 'ministries'],
  economy: ['indicators', 'monetary-policy', 'sectors', 'policy', 'institutions', 'trade'],
  // Civic terms first — the glossary's job is explaining the state to a reader.
  glossary: ['government', 'legal', 'corporate', 'tax', 'employment', 'culture'],
};

function titleCase(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

export function subcatLabel(slug: string, locale: Locale): string {
  return SUBCATEGORY_LABELS[slug]?.[locale as ContentLocale] ?? titleCase(slug);
}

/** Ordered subcategory slugs present in a set of articles. */
export function orderedSubcats(categoryId: string, present: string[]): string[] {
  const order = SUBCATEGORY_ORDER[categoryId] ?? [];
  const seen = [...new Set(present)];
  return seen.sort((a, b) => {
    const ia = order.indexOf(a);
    const ib = order.indexOf(b);
    return (ia === -1 ? 999 : ia) - (ib === -1 ? 999 : ib);
  });
}
