// @ts-check
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';

// Canonical production URL (kept in sync with src/lib/site.ts).
const SITE = 'https://negaraku.md';

// Build a `${lang}/${category}/${slug}` → last-changed date map from the article
// manifest (generated by scripts/sync.mjs at pre{dev,build}), so the sitemap can
// emit <lastmod>. Missing/unbuilt manifest → empty map → no lastmod, never fails.
const lastmodByPath = (() => {
  const map = new Map();
  try {
    const file = fileURLToPath(new URL('./public/api/articles.json', import.meta.url));
    const { articles } = JSON.parse(readFileSync(file, 'utf8'));
    for (const a of articles) {
      if (!a.category || !a.slug) continue;
      const date = a.updated ?? a.reviewed ?? a.published; // YYYY-MM-DD or null
      if (!date) continue;
      map.set(`${a.lang ?? 'ms'}/${a.category}/${a.slug}`, date);
    }
  } catch {
    /* manifest not built yet — sitemap simply omits lastmod */
  }
  return map;
})();

/** Map a sitemap URL back to a manifest key: strip origin, locale prefix, slashes. */
function lastmodFor(url) {
  let p = url.replace(SITE, '').replace(/^\/+|\/+$/g, ''); // e.g. "en/malaysia/slug"
  if (!p) return undefined; // homepage
  const seg = p.split('/');
  const lang = seg[0] === 'en' || seg[0] === 'zh' ? seg.shift() : 'ms';
  if (seg.length < 2) return undefined; // category/list page, not an article
  return lastmodByPath.get(`${lang}/${seg.join('/')}`);
}

// https://astro.build/config
// Redirects for retired duplicate articles → their canonical merge target.
// GitHub Pages is static, so Astro emits an HTML redirect page per entry with a
// <meta http-equiv="refresh"> and a <link rel="canonical"> — the Google/Bing-
// accepted way to consolidate a URL on a static host (preserves link equity,
// avoids a 404). One entry per locale (ms at "/", en at "/en", zh at "/zh").
// The retired slugs are archived in content, so the article route no longer
// emits them and these redirects own the paths with no collision.
const redirects = {
  '/government/national-registration-department-jpn': '/government/jpn',
  '/en/government/national-registration-department-jpn': '/en/government/jpn',
  '/zh/government/national-registration-department-jpn': '/zh/government/jpn',
  '/government/ministry-of-investment-trade-industry-miti': '/government/miti',
  '/en/government/ministry-of-investment-trade-industry-miti': '/en/government/miti',
  '/zh/government/ministry-of-investment-trade-industry-miti': '/zh/government/miti',
  '/glossary/bank-negara-malaysia': '/economy/bank-negara-malaysia',
  '/en/glossary/bank-negara-malaysia': '/en/economy/bank-negara-malaysia',
  '/zh/glossary/bank-negara-malaysia': '/zh/economy/bank-negara-malaysia',
  '/government/bank-negara-malaysia': '/economy/bank-negara-malaysia',
  '/en/government/bank-negara-malaysia': '/en/economy/bank-negara-malaysia',
  '/zh/government/bank-negara-malaysia': '/zh/economy/bank-negara-malaysia',
  '/energy/petronas': '/companies/petronas',
  '/en/energy/petronas': '/en/companies/petronas',
  '/zh/energy/petronas': '/zh/companies/petronas',
  '/industries/petronas-industry-profile': '/companies/petronas',
  '/en/industries/petronas-industry-profile': '/en/companies/petronas',
  '/zh/industries/petronas-industry-profile': '/zh/companies/petronas',
  '/law/personal-data-protection-act-2010': '/law/pdpa-2010',
  '/en/law/personal-data-protection-act-2010': '/en/law/pdpa-2010',
  '/zh/law/personal-data-protection-act-2010': '/zh/law/pdpa-2010',
  '/business/cyber-security-act-malaysia': '/technology/cyber-security-act-2024',
  '/en/business/cyber-security-act-malaysia': '/en/technology/cyber-security-act-2024',
  '/zh/business/cyber-security-act-malaysia': '/zh/technology/cyber-security-act-2024',
  '/companies/pnb-and-asnb': '/economy/pnb',
  '/en/companies/pnb-and-asnb': '/en/economy/pnb',
  '/zh/companies/pnb-and-asnb': '/zh/economy/pnb',
  '/glossary/felda': '/agriculture/felda-land-settlement-scheme',
  '/en/glossary/felda': '/en/agriculture/felda-land-settlement-scheme',
  '/zh/glossary/felda': '/zh/agriculture/felda-land-settlement-scheme',
  '/glossary/orang-asli': '/arts-culture/orang-asli',
  '/en/glossary/orang-asli': '/en/arts-culture/orang-asli',
  '/zh/glossary/orang-asli': '/zh/arts-culture/orang-asli',
  '/energy/tnb-tenaga-nasional': '/companies/tenaga-nasional',
  '/en/energy/tnb-tenaga-nasional': '/en/companies/tenaga-nasional',
  '/zh/energy/tnb-tenaga-nasional': '/zh/companies/tenaga-nasional',
  '/companies/khazanah-nasional': '/economy/khazanah',
  '/en/companies/khazanah-nasional': '/en/economy/khazanah',
  '/zh/companies/khazanah-nasional': '/zh/economy/khazanah',
  '/glossary/khazanah-nasional': '/economy/khazanah',
  '/en/glossary/khazanah-nasional': '/en/economy/khazanah',
  '/zh/glossary/khazanah-nasional': '/zh/economy/khazanah',
  '/economy/deposit-insurance-pidm': '/finance/pidm-deposit-and-takaful-insurance-protection',
  '/en/economy/deposit-insurance-pidm': '/en/finance/pidm-deposit-and-takaful-insurance-protection',
  '/zh/economy/deposit-insurance-pidm': '/zh/finance/pidm-deposit-and-takaful-insurance-protection',
};

export default defineConfig({
  site: SITE,
  trailingSlash: 'ignore',
  redirects,
  // Honor a harness/CI-assigned PORT (enables preview autoPort when 4321 is
  // busy); fall back to Astro's default 4321 for a plain `npm run dev`.
  server: { port: Number(process.env.PORT) || 4321, host: true },
  vite: {
    server: {
      // Let the dev server be reached through a Cloudflare quick tunnel — the
      // host is a random *.trycloudflare.com, which Vite otherwise blocks (403).
      // Dev-only; has no effect on `astro build` / production.
      allowedHosts: ['.trycloudflare.com'],
    },
  },
  i18n: {
    defaultLocale: 'ms',
    locales: ['ms', 'en', 'zh'],
    routing: {
      prefixDefaultLocale: false, // ms lives at "/", en at "/en", zh at "/zh"
    },
  },
  integrations: [
    mdx(),
    sitemap({
      i18n: {
        defaultLocale: 'ms',
        locales: { ms: 'ms-MY', en: 'en', zh: 'zh-Hans' },
      },
      serialize(item) {
        const lastmod = lastmodFor(item.url);
        if (lastmod) item.lastmod = lastmod;
        return item;
      },
    }),
  ],
  markdown: {
    shikiConfig: { theme: 'github-light', wrap: true },
  },
});
