// @ts-check
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import { FontaineTransform } from 'fontaine';

// Canonical production URL (kept in sync with src/lib/site.ts).
const SITE = 'https://negaraku.md';

// Build a `${lang}/${category}/${slug}` → last-changed date map from the article
// manifest (generated by scripts/sync.mjs at pre{dev,build}), so the sitemap can
// emit <lastmod>. Missing/unbuilt manifest → empty map → no lastmod, never fails.
const lastmodByPath = (() => {
  const map = new Map();
  try {
    const file = fileURLToPath(new URL('./public/api/articles.json', import.meta.url));
    const { articles } = JSON.parse(readFileSync(file, 'utf8'));
    for (const a of articles) {
      if (!a.category || !a.slug) continue;
      const date = a.updated ?? a.reviewed ?? a.published; // YYYY-MM-DD or null
      if (!date) continue;
      map.set(`${a.lang ?? 'ms'}/${a.category}/${a.slug}`, date);
    }
  } catch {
    /* manifest not built yet — sitemap simply omits lastmod */
  }
  return map;
})();

/** Map a sitemap URL back to a manifest key: strip origin, locale prefix, slashes. */
function lastmodFor(url) {
  let p = url.replace(SITE, '').replace(/^\/+|\/+$/g, ''); // e.g. "en/malaysia/slug"
  if (!p) return undefined; // homepage
  const seg = p.split('/');
  const lang = seg[0] === 'en' || seg[0] === 'zh' || seg[0] === 'ta' || seg[0] === 'ja' ? seg.shift() : 'ms';
  if (seg.length < 2) return undefined; // category/list page, not an article
  return lastmodByPath.get(`${lang}/${seg.join('/')}`);
}

// https://astro.build/config
// Redirects for retired duplicate articles → their canonical merge target.
// GitHub Pages is static, so Astro emits an HTML redirect page per entry with a
// <meta http-equiv="refresh"> and a <link rel="canonical"> — the Google/Bing-
// accepted way to consolidate a URL on a static host (preserves link equity,
// avoids a 404). One entry per locale (ms at "/", en at "/en", zh at "/zh").
// The retired slugs are archived in content, so the article route no longer
// emits them and these redirects own the paths with no collision.
const redirects = {
  '/government/national-registration-department-jpn': '/government/jpn',
  '/en/government/national-registration-department-jpn': '/en/government/jpn',
  '/zh/government/national-registration-department-jpn': '/zh/government/jpn',
  '/government/ministry-of-investment-trade-industry-miti': '/government/miti',
  '/en/government/ministry-of-investment-trade-industry-miti': '/en/government/miti',
  '/zh/government/ministry-of-investment-trade-industry-miti': '/zh/government/miti',
  '/glossary/bank-negara-malaysia': '/economy/bank-negara-malaysia',
  '/en/glossary/bank-negara-malaysia': '/en/economy/bank-negara-malaysia',
  '/zh/glossary/bank-negara-malaysia': '/zh/economy/bank-negara-malaysia',
  '/government/bank-negara-malaysia': '/economy/bank-negara-malaysia',
  '/en/government/bank-negara-malaysia': '/en/economy/bank-negara-malaysia',
  '/zh/government/bank-negara-malaysia': '/zh/economy/bank-negara-malaysia',
  '/energy/petronas': '/companies/petronas',
  '/en/energy/petronas': '/en/companies/petronas',
  '/zh/energy/petronas': '/zh/companies/petronas',
  '/industries/petronas-industry-profile': '/companies/petronas',
  '/en/industries/petronas-industry-profile': '/en/companies/petronas',
  '/zh/industries/petronas-industry-profile': '/zh/companies/petronas',
  '/law/personal-data-protection-act-2010': '/law/pdpa-2010',
  '/en/law/personal-data-protection-act-2010': '/en/law/pdpa-2010',
  '/zh/law/personal-data-protection-act-2010': '/zh/law/pdpa-2010',
  '/business/cyber-security-act-malaysia': '/technology/cyber-security-act-2024',
  '/en/business/cyber-security-act-malaysia': '/en/technology/cyber-security-act-2024',
  '/zh/business/cyber-security-act-malaysia': '/zh/technology/cyber-security-act-2024',
  '/companies/pnb-and-asnb': '/economy/pnb',
  '/en/companies/pnb-and-asnb': '/en/economy/pnb',
  '/zh/companies/pnb-and-asnb': '/zh/economy/pnb',
  '/glossary/felda': '/agriculture/felda-land-settlement-scheme',
  '/en/glossary/felda': '/en/agriculture/felda-land-settlement-scheme',
  '/zh/glossary/felda': '/zh/agriculture/felda-land-settlement-scheme',
  '/glossary/orang-asli': '/arts-culture/orang-asli',
  '/en/glossary/orang-asli': '/en/arts-culture/orang-asli',
  '/zh/glossary/orang-asli': '/zh/arts-culture/orang-asli',
  '/energy/tnb-tenaga-nasional': '/companies/tenaga-nasional',
  '/en/energy/tnb-tenaga-nasional': '/en/companies/tenaga-nasional',
  '/zh/energy/tnb-tenaga-nasional': '/zh/companies/tenaga-nasional',
  '/companies/khazanah-nasional': '/economy/khazanah',
  '/en/companies/khazanah-nasional': '/en/economy/khazanah',
  '/zh/companies/khazanah-nasional': '/zh/economy/khazanah',
  '/glossary/khazanah-nasional': '/economy/khazanah',
  '/en/glossary/khazanah-nasional': '/en/economy/khazanah',
  '/zh/glossary/khazanah-nasional': '/zh/economy/khazanah',
  '/economy/deposit-insurance-pidm': '/finance/pidm-deposit-and-takaful-insurance-protection',
  '/en/economy/deposit-insurance-pidm': '/en/finance/pidm-deposit-and-takaful-insurance-protection',
  '/zh/economy/deposit-insurance-pidm': '/zh/finance/pidm-deposit-and-takaful-insurance-protection',
  '/glossary/polis-diraja-malaysia': '/government/pdrm',
  '/en/glossary/polis-diraja-malaysia': '/en/government/pdrm',
  '/zh/glossary/polis-diraja-malaysia': '/zh/government/pdrm',
  '/public-safety/royal-malaysia-police-pdrm': '/government/pdrm',
  '/en/public-safety/royal-malaysia-police-pdrm': '/en/government/pdrm',
  '/zh/public-safety/royal-malaysia-police-pdrm': '/zh/government/pdrm',
  '/glossary/suruhanjaya-pilihan-raya': '/government/spr-election-commission',
  '/en/glossary/suruhanjaya-pilihan-raya': '/en/government/spr-election-commission',
  '/zh/glossary/suruhanjaya-pilihan-raya': '/zh/government/spr-election-commission',
  '/technology/mcmc-malaysia': '/government/mcmc-communications-multimedia-commission',
  '/en/technology/mcmc-malaysia': '/en/government/mcmc-communications-multimedia-commission',
  '/zh/technology/mcmc-malaysia': '/zh/government/mcmc-communications-multimedia-commission',
  '/government/ma63-sabah-sarawak-autonomy': '/malaysia/ma63',
  '/en/government/ma63-sabah-sarawak-autonomy': '/en/malaysia/ma63',
  '/zh/government/ma63-sabah-sarawak-autonomy': '/zh/malaysia/ma63',
  '/glossary/dasar-ekonomi-baru': '/malaysia/new-economic-policy',
  '/en/glossary/dasar-ekonomi-baru': '/en/malaysia/new-economic-policy',
  '/zh/glossary/dasar-ekonomi-baru': '/zh/malaysia/new-economic-policy',
  // /ja and /ta mirrors of every retired-dupe redirect above, so the Japanese
  // and Tamil old URLs consolidate to their canonical page exactly like ms/en/zh
  // (added 2026-09-20; the .ja dupes are archived like their ms/en/zh siblings).
  '/ja/government/national-registration-department-jpn': '/ja/government/jpn',
  '/ta/government/national-registration-department-jpn': '/ta/government/jpn',
  '/ja/government/ministry-of-investment-trade-industry-miti': '/ja/government/miti',
  '/ta/government/ministry-of-investment-trade-industry-miti': '/ta/government/miti',
  '/ja/glossary/bank-negara-malaysia': '/ja/economy/bank-negara-malaysia',
  '/ta/glossary/bank-negara-malaysia': '/ta/economy/bank-negara-malaysia',
  '/ja/government/bank-negara-malaysia': '/ja/economy/bank-negara-malaysia',
  '/ta/government/bank-negara-malaysia': '/ta/economy/bank-negara-malaysia',
  '/ja/energy/petronas': '/ja/companies/petronas',
  '/ta/energy/petronas': '/ta/companies/petronas',
  '/ja/industries/petronas-industry-profile': '/ja/companies/petronas',
  '/ta/industries/petronas-industry-profile': '/ta/companies/petronas',
  '/ja/law/personal-data-protection-act-2010': '/ja/law/pdpa-2010',
  '/ta/law/personal-data-protection-act-2010': '/ta/law/pdpa-2010',
  '/ja/business/cyber-security-act-malaysia': '/ja/technology/cyber-security-act-2024',
  '/ta/business/cyber-security-act-malaysia': '/ta/technology/cyber-security-act-2024',
  '/ja/companies/pnb-and-asnb': '/ja/economy/pnb',
  '/ta/companies/pnb-and-asnb': '/ta/economy/pnb',
  '/ja/glossary/felda': '/ja/agriculture/felda-land-settlement-scheme',
  '/ta/glossary/felda': '/ta/agriculture/felda-land-settlement-scheme',
  '/ja/glossary/orang-asli': '/ja/arts-culture/orang-asli',
  '/ta/glossary/orang-asli': '/ta/arts-culture/orang-asli',
  '/ja/energy/tnb-tenaga-nasional': '/ja/companies/tenaga-nasional',
  '/ta/energy/tnb-tenaga-nasional': '/ta/companies/tenaga-nasional',
  '/ja/companies/khazanah-nasional': '/ja/economy/khazanah',
  '/ta/companies/khazanah-nasional': '/ta/economy/khazanah',
  '/ja/glossary/khazanah-nasional': '/ja/economy/khazanah',
  '/ta/glossary/khazanah-nasional': '/ta/economy/khazanah',
  '/ja/economy/deposit-insurance-pidm': '/ja/finance/pidm-deposit-and-takaful-insurance-protection',
  '/ta/economy/deposit-insurance-pidm': '/ta/finance/pidm-deposit-and-takaful-insurance-protection',
  '/ja/glossary/polis-diraja-malaysia': '/ja/government/pdrm',
  '/ta/glossary/polis-diraja-malaysia': '/ta/government/pdrm',
  '/ja/public-safety/royal-malaysia-police-pdrm': '/ja/government/pdrm',
  '/ta/public-safety/royal-malaysia-police-pdrm': '/ta/government/pdrm',
  '/ja/glossary/suruhanjaya-pilihan-raya': '/ja/government/spr-election-commission',
  '/ta/glossary/suruhanjaya-pilihan-raya': '/ta/government/spr-election-commission',
  '/ja/technology/mcmc-malaysia': '/ja/government/mcmc-communications-multimedia-commission',
  '/ta/technology/mcmc-malaysia': '/ta/government/mcmc-communications-multimedia-commission',
  '/ja/government/ma63-sabah-sarawak-autonomy': '/ja/malaysia/ma63',
  '/ta/government/ma63-sabah-sarawak-autonomy': '/ta/malaysia/ma63',
  '/ja/glossary/dasar-ekonomi-baru': '/ja/malaysia/new-economic-policy',
  '/ta/glossary/dasar-ekonomi-baru': '/ta/malaysia/new-economic-policy',
  // /ko mirrors of every retired-dupe redirect above (added 2026-09-26 at Korean
  // open launch; the .ko dupes are archived like their ms/en/zh/ta/ja siblings).
  '/ko/government/national-registration-department-jpn': '/ko/government/jpn',
  '/ko/government/ministry-of-investment-trade-industry-miti': '/ko/government/miti',
  '/ko/glossary/bank-negara-malaysia': '/ko/economy/bank-negara-malaysia',
  '/ko/government/bank-negara-malaysia': '/ko/economy/bank-negara-malaysia',
  '/ko/energy/petronas': '/ko/companies/petronas',
  '/ko/industries/petronas-industry-profile': '/ko/companies/petronas',
  '/ko/law/personal-data-protection-act-2010': '/ko/law/pdpa-2010',
  '/ko/business/cyber-security-act-malaysia': '/ko/technology/cyber-security-act-2024',
  '/ko/companies/pnb-and-asnb': '/ko/economy/pnb',
  '/ko/glossary/felda': '/ko/agriculture/felda-land-settlement-scheme',
  '/ko/glossary/orang-asli': '/ko/arts-culture/orang-asli',
  '/ko/energy/tnb-tenaga-nasional': '/ko/companies/tenaga-nasional',
  '/ko/companies/khazanah-nasional': '/ko/economy/khazanah',
  '/ko/glossary/khazanah-nasional': '/ko/economy/khazanah',
  '/ko/economy/deposit-insurance-pidm': '/ko/finance/pidm-deposit-and-takaful-insurance-protection',
  '/ko/glossary/polis-diraja-malaysia': '/ko/government/pdrm',
  '/ko/public-safety/royal-malaysia-police-pdrm': '/ko/government/pdrm',
  '/ko/glossary/suruhanjaya-pilihan-raya': '/ko/government/spr-election-commission',
  '/ko/technology/mcmc-malaysia': '/ko/government/mcmc-communications-multimedia-commission',
  '/ko/government/ma63-sabah-sarawak-autonomy': '/ko/malaysia/ma63',
  '/ko/glossary/dasar-ekonomi-baru': '/ko/malaysia/new-economic-policy',
  // /th mirrors of every retired-dupe redirect above (added 2026-09-27 at Thai
  // open launch; the .th dupes are archived like their ms/en/zh/ta/ja/ko siblings).
  '/th/government/national-registration-department-jpn': '/th/government/jpn',
  '/th/government/ministry-of-investment-trade-industry-miti': '/th/government/miti',
  '/th/glossary/bank-negara-malaysia': '/th/economy/bank-negara-malaysia',
  '/th/government/bank-negara-malaysia': '/th/economy/bank-negara-malaysia',
  '/th/energy/petronas': '/th/companies/petronas',
  '/th/industries/petronas-industry-profile': '/th/companies/petronas',
  '/th/law/personal-data-protection-act-2010': '/th/law/pdpa-2010',
  '/th/business/cyber-security-act-malaysia': '/th/technology/cyber-security-act-2024',
  '/th/companies/pnb-and-asnb': '/th/economy/pnb',
  '/th/glossary/felda': '/th/agriculture/felda-land-settlement-scheme',
  '/th/glossary/orang-asli': '/th/arts-culture/orang-asli',
  '/th/energy/tnb-tenaga-nasional': '/th/companies/tenaga-nasional',
  '/th/companies/khazanah-nasional': '/th/economy/khazanah',
  '/th/glossary/khazanah-nasional': '/th/economy/khazanah',
  '/th/economy/deposit-insurance-pidm': '/th/finance/pidm-deposit-and-takaful-insurance-protection',
  '/th/glossary/polis-diraja-malaysia': '/th/government/pdrm',
  '/th/public-safety/royal-malaysia-police-pdrm': '/th/government/pdrm',
  '/th/glossary/suruhanjaya-pilihan-raya': '/th/government/spr-election-commission',
  '/th/technology/mcmc-malaysia': '/th/government/mcmc-communications-multimedia-commission',
  '/th/government/ma63-sabah-sarawak-autonomy': '/th/malaysia/ma63',
  '/th/glossary/dasar-ekonomi-baru': '/th/malaysia/new-economic-policy',
  // /vi mirrors of every retired-dupe redirect above (added 2026-09-29 at Vietnamese
  // open launch; the .vi dupes are archived like their ms/en/zh/ta/ja/ko/th siblings).
  '/vi/government/national-registration-department-jpn': '/vi/government/jpn',
  '/vi/government/ministry-of-investment-trade-industry-miti': '/vi/government/miti',
  '/vi/glossary/bank-negara-malaysia': '/vi/economy/bank-negara-malaysia',
  '/vi/government/bank-negara-malaysia': '/vi/economy/bank-negara-malaysia',
  '/vi/energy/petronas': '/vi/companies/petronas',
  '/vi/industries/petronas-industry-profile': '/vi/companies/petronas',
  '/vi/law/personal-data-protection-act-2010': '/vi/law/pdpa-2010',
  '/vi/business/cyber-security-act-malaysia': '/vi/technology/cyber-security-act-2024',
  '/vi/companies/pnb-and-asnb': '/vi/economy/pnb',
  '/vi/glossary/felda': '/vi/agriculture/felda-land-settlement-scheme',
  '/vi/glossary/orang-asli': '/vi/arts-culture/orang-asli',
  '/vi/energy/tnb-tenaga-nasional': '/vi/companies/tenaga-nasional',
  '/vi/companies/khazanah-nasional': '/vi/economy/khazanah',
  '/vi/glossary/khazanah-nasional': '/vi/economy/khazanah',
  '/vi/economy/deposit-insurance-pidm': '/vi/finance/pidm-deposit-and-takaful-insurance-protection',
  '/vi/glossary/polis-diraja-malaysia': '/vi/government/pdrm',
  '/vi/public-safety/royal-malaysia-police-pdrm': '/vi/government/pdrm',
  '/vi/glossary/suruhanjaya-pilihan-raya': '/vi/government/spr-election-commission',
  '/vi/technology/mcmc-malaysia': '/vi/government/mcmc-communications-multimedia-commission',
  '/vi/government/ma63-sabah-sarawak-autonomy': '/vi/malaysia/ma63',
  '/vi/glossary/dasar-ekonomi-baru': '/vi/malaysia/new-economic-policy',
  // /id mirrors of every retired-dupe redirect above (added 2026-10-04 at Indonesian
  // open launch; the .id dupes are archived like their ms/en/zh/ta/ja/ko/th/vi siblings).
  '/id/government/national-registration-department-jpn': '/id/government/jpn',
  '/id/government/ministry-of-investment-trade-industry-miti': '/id/government/miti',
  '/id/glossary/bank-negara-malaysia': '/id/economy/bank-negara-malaysia',
  '/id/government/bank-negara-malaysia': '/id/economy/bank-negara-malaysia',
  '/id/energy/petronas': '/id/companies/petronas',
  '/id/industries/petronas-industry-profile': '/id/companies/petronas',
  '/id/law/personal-data-protection-act-2010': '/id/law/pdpa-2010',
  '/id/business/cyber-security-act-malaysia': '/id/technology/cyber-security-act-2024',
  '/id/companies/pnb-and-asnb': '/id/economy/pnb',
  '/id/glossary/felda': '/id/agriculture/felda-land-settlement-scheme',
  '/id/glossary/orang-asli': '/id/arts-culture/orang-asli',
  '/id/energy/tnb-tenaga-nasional': '/id/companies/tenaga-nasional',
  '/id/companies/khazanah-nasional': '/id/economy/khazanah',
  '/id/glossary/khazanah-nasional': '/id/economy/khazanah',
  '/id/economy/deposit-insurance-pidm': '/id/finance/pidm-deposit-and-takaful-insurance-protection',
  '/id/glossary/polis-diraja-malaysia': '/id/government/pdrm',
  '/id/public-safety/royal-malaysia-police-pdrm': '/id/government/pdrm',
  '/id/glossary/suruhanjaya-pilihan-raya': '/id/government/spr-election-commission',
  '/id/technology/mcmc-malaysia': '/id/government/mcmc-communications-multimedia-commission',
  '/id/government/ma63-sabah-sarawak-autonomy': '/id/malaysia/ma63',
  '/id/glossary/dasar-ekonomi-baru': '/id/malaysia/new-economic-policy',
};

export default defineConfig({
  site: SITE,
  trailingSlash: 'ignore',
  redirects,
  // NOTE: inlineStylesheets:'always' was tried to kill the ~800 ms render-blocking
  // CSS, but inlining into ~9,700 pages OOM'd the build (6144 MB) and ~2x'd build
  // time. Not worth it on a site this size / already at LCP 2.1s + CWV passed.
  // Left at Astro's default 'auto'. A future render-blocking fix would need
  // critical-CSS extraction or a preload trick, not blanket inlining.
  // Hide the floating Astro dev-toolbar island in `npm run dev` — it only ever
  // appears in development (never in the production build), but it clutters
  // visual reviews/screenshots. Turn back on if you need its audits.
  devToolbar: { enabled: false },
  // Honor a harness/CI-assigned PORT (enables preview autoPort when 4321 is
  // busy); fall back to Astro's default 4321 for a plain `npm run dev`.
  server: { port: Number(process.env.PORT) || 4321, host: true },
  vite: {
    // Ship modern JS to evergreen browsers — avoids esbuild down-levelling and
    // the polyfills Lighthouse flagged as "legacy JavaScript" (~11 KB). es2022
    // (class fields, top-level await, Array.at, Object.hasOwn) is supported by
    // every browser this site targets.
    build: { target: 'es2022' },
    plugins: [
      // Generate metric-adjusted fallback @font-faces for the self-hosted brand
      // fonts (size-adjust / ascent/descent/line-gap-override tuned from each
      // family's real metrics) and splice them into the font-family stacks. The
      // fallback then occupies the same space as Montserrat/Lato, so the hero
      // text does not reflow when the web font swaps in — kills the font-swap
      // CLS seen on throttled mobile. Metrics come from fontaine's built-in DB.
      FontaineTransform.vite({
        fallbacks: ['Arial', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'sans-serif'],
      }),
    ],
    server: {
      // Let the dev server be reached through a Cloudflare quick tunnel — the
      // host is a random *.trycloudflare.com, which Vite otherwise blocks (403).
      // Dev-only; has no effect on `astro build` / production.
      allowedHosts: ['.trycloudflare.com'],
      // Full-stack local testing: with LOCAL_WORKERS=1 and the two Workers running
      // via `wrangler dev` (npm run dev:full — see docs/LOCAL-DEV.md), proxy their
      // paths so login/auth (/api/auth/*) and the analytics beacon (/_a/*) work on
      // http://localhost:4321 — the SAME origin, so the session cookie round-trips.
      // changeOrigin:false keeps the Host as localhost so the OAuth callback matches.
      // No effect on build/prod, and no effect when LOCAL_WORKERS is unset.
      proxy: process.env.LOCAL_WORKERS
        ? {
            '/api/auth': { target: 'http://127.0.0.1:8788', changeOrigin: false },
            '/_a': { target: 'http://127.0.0.1:8787', changeOrigin: false },
          }
        : undefined,
    },
  },
  i18n: {
    defaultLocale: 'ms',
    locales: ['ms', 'en', 'zh', 'ta', 'ja', 'ko', 'th', 'vi', 'id'],
    routing: {
      prefixDefaultLocale: false, // ms at "/", en /en, zh /zh, ta /ta, ja /ja, ko /ko, th /th, vi /vi, id /id
    },
  },
  integrations: [
    mdx(),
    sitemap({
      // ms/en/zh/ta/ja/ko/th/vi/id are all fully launched (in LOCALES, indexed, in this
      // sitemap). Indonesian (`id`) opened 2026-10-04 (Phase 3): the soft-launch filter that
      // held /id out of the sitemap was removed and id added to LOCALES + the locales map.
      i18n: {
        defaultLocale: 'ms',
        locales: { ms: 'ms-MY', en: 'en', zh: 'zh-Hans', ta: 'ta', ja: 'ja', ko: 'ko', th: 'th', vi: 'vi', id: 'id' },
      },
      serialize(item) {
        const lastmod = lastmodFor(item.url);
        if (lastmod) item.lastmod = lastmod;
        return item;
      },
    }),
  ],
  markdown: {
    shikiConfig: { theme: 'github-light', wrap: true },
  },
});
