// @ts-check
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';

// Canonical production URL (kept in sync with src/lib/site.ts).
const SITE = 'https://negaraku.md';

// Build a `${lang}/${category}/${slug}` → last-changed date map from the article
// manifest (generated by scripts/sync.mjs at pre{dev,build}), so the sitemap can
// emit <lastmod>. Missing/unbuilt manifest → empty map → no lastmod, never fails.
const lastmodByPath = (() => {
  const map = new Map();
  try {
    const file = fileURLToPath(new URL('./public/api/articles.json', import.meta.url));
    const { articles } = JSON.parse(readFileSync(file, 'utf8'));
    for (const a of articles) {
      if (!a.category || !a.slug) continue;
      const date = a.updated ?? a.reviewed ?? a.published; // YYYY-MM-DD or null
      if (!date) continue;
      map.set(`${a.lang ?? 'ms'}/${a.category}/${a.slug}`, date);
    }
  } catch {
    /* manifest not built yet — sitemap simply omits lastmod */
  }
  return map;
})();

/** Map a sitemap URL back to a manifest key: strip origin, locale prefix, slashes. */
function lastmodFor(url) {
  let p = url.replace(SITE, '').replace(/^\/+|\/+$/g, ''); // e.g. "en/malaysia/slug"
  if (!p) return undefined; // homepage
  const seg = p.split('/');
  const lang = seg[0] === 'en' || seg[0] === 'zh' ? seg.shift() : 'ms';
  if (seg.length < 2) return undefined; // category/list page, not an article
  return lastmodByPath.get(`${lang}/${seg.join('/')}`);
}

// https://astro.build/config
export default defineConfig({
  site: SITE,
  trailingSlash: 'ignore',
  // Honor a harness/CI-assigned PORT (enables preview autoPort when 4321 is
  // busy); fall back to Astro's default 4321 for a plain `npm run dev`.
  server: { port: Number(process.env.PORT) || 4321, host: true },
  vite: {
    server: {
      // Let the dev server be reached through a Cloudflare quick tunnel — the
      // host is a random *.trycloudflare.com, which Vite otherwise blocks (403).
      // Dev-only; has no effect on `astro build` / production.
      allowedHosts: ['.trycloudflare.com'],
    },
  },
  i18n: {
    defaultLocale: 'ms',
    locales: ['ms', 'en', 'zh'],
    routing: {
      prefixDefaultLocale: false, // ms lives at "/", en at "/en", zh at "/zh"
    },
  },
  integrations: [
    mdx(),
    sitemap({
      i18n: {
        defaultLocale: 'ms',
        locales: { ms: 'ms-MY', en: 'en', zh: 'zh-Hans' },
      },
      serialize(item) {
        const lastmod = lastmodFor(item.url);
        if (lastmod) item.lastmod = lastmod;
        return item;
      },
    }),
  ],
  markdown: {
    shikiConfig: { theme: 'github-light', wrap: true },
  },
});
